### ISSUE TITLE
不管我把文件名怎么改最后的服务都是目录+winsw.exe    (win11)

### ISSUE THREAD

**Issue by moyefu** [winsw/winsw#1005]
### Problem statement

Please describe your issue here, and explain what you have already tried to resolve it.

![image](https://user-images.githubusercontent.com/57945333/215371849-43f451a6-6ee9-4c81-9c32-312f7c6434a8.png)

**Comment by moyefu** [comment]
![image](https://user-images.githubusercontent.com/57945333/215371997-67c47d92-e5c1-47fc-8338-13eff3f29f0f.png)

**Comment by nxtn** [comment]
This is how WinSW is designed to work. If your program is a service application you can use [sc.exe create](https://learn.microsoft.com/windows-server/administration/windows-commands/sc-create) to install the service.

**Comment by moyefu** [comment]
好的 感谢
