### ISSUE TITLE
Unable to start service as specific user

### ISSUE THREAD

**Issue by liu-jianyang** [winsw/winsw#109]
So, in the xml, I have 
`<service>
  <id>
  <description>
  ...
  <serviceaccount>
    <domain>domain</domain>
    <user>username</user>
    <password>pass123</password>
    <allowservicelogon>true</allowservicelogon>
  </serviceaccount>
</service>`

However, when I ran the .exe with install, and then start, Services still indicate that the this service is logged on as "Local System."

Anyone know if this is a bug, or if there's something I'm doing wrong?

Thanks!

**Comment by oleg-nenashev** [comment]
Which Windows version do you use?
And just to be sure... Have you modified the file before launching <code>app.exe install</code> or after it?

**Comment by liu-jianyang** [comment]
I'm using Win7 x64.

I modified the file before, and checked that the xml file includes the serviceaccount node.

**Comment by oleg-nenashev** [comment]
Sorry for the missing response, missed this issue update.
I'm pretty sure I've tested this case some time ago, but I will re-check it

**Comment by NextTurn** [comment]
I can't reproduce this.
