### ISSUE TITLE
The specified service does not exist as an installed service. (Exception from HRESULT: 0x80070424)

### ISSUE THREAD

**Issue by skorob** [winsw/winsw#111]
When I start install command it raises the following exception:

System.Runtime.InteropServices.COMException (0x80070424): The specified service does not exist as an installed service. (Exception from HRESULT: 0x80070424)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at WMI.WmiRoot..ctor(String machineName)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

**Comment by oleg-nenashev** [comment]
Is it still actual? It's hard to say what has happened without additional info

**Comment by Blak-Ish** [comment]
Currently facing this as well ... need help

**Comment by crazyx13th** [comment]
I got he nearly (0x80070422) the same if I call `app.exe install`: 

```
System.Runtime.InteropServices.COMException (0x80070422): Der angegebene Dienst kann nicht gestartet werden. Er ist deaktiviert oder nicht mit aktivierten Ger�ten verbunden. (Ausnahme von HRESULT: 0x80070422)
   bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bei System.Management.ManagementScope.InitializeGuts(Object o)
   bei System.Management.ManagementScope.Initialize()
   bei WMI.WmiRoot..ctor(String machineName)
   bei winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   bei winsw.WrapperService.Main(String[] args)
```

**Comment by crazyx13th** [comment]
I tried
`dism.exe /online /cleanup-image /scanhealth`
`dism.exe /online /cleanup-image /restorehealth`
`sfc /scannow`

... nothing new :-/
