### ISSUE TITLE
How to determine that the program will be stopped?

### ISSUE THREAD

**Issue by heretic13** [winsw/winsw#115]
Hello.

There is a console program. How do I intercept the event of closure and perform some action on the freeing of resources?

Interception SIGINT does not work. 

Messages from log:
2016-05-29 11:27:56 - Send SIGINT 8368
2016-05-29 11:27:56 - SIGINT to 8368 failed - Killing as fallback

I think problem in 'AttachConsole'.

OS: Windows 10 x64

**Comment by heretic13** [comment]
Relly simple code in go to test it
`
package main

import (
	"fmt"
	"os"
	"os/signal"
)

func main() {
	// Set up channel on which to send signal notifications.
	// We must use a buffered channel or risk missing the signal
	// if we're not ready to receive when the signal is sent.
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)

	// Block until a signal is received.
	s := <-c
	fmt.Println("Got signal:", s)
}
`
It works when yourself push Ctrl-C, but I do not see a message about closing when working through the wrapper

**Comment by heretic13** [comment]
ModifyProgram

-------------------------------------
package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"os/signal"
)

func main() {

	fmt.Println("hello")

	// Set up channel on which to send signal notifications.
	// We must use a buffered channel or risk missing the signal
	// if we're not ready to receive when the signal is sent.
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)

	// Block until a signal is received.
	s := <-c
	fmt.Println("Got signal:", s)

	d1 := []byte("hello\ngo\n")
	ioutil.WriteFile("dat1", d1, 0644)
}
-------------------------------------

File not created.

**Comment by oleg-nenashev** [comment]
Most likely it's a Windows service specifics.
Need to RTFM about the signal handling behavior in this case.
