### ISSUE TITLE
The system cannot find the file specified...

### ISSUE THREAD

**Issue by cjparsons** [winsw/winsw#116]
First time using winsw,,,

Getting an event error when starting the service, "Win32Exception: The system cannot find the file specified"

The executable path is correct, app runs when this path is called from the command line?

Path has embedded spaces so I have tried quoting the path but didn't make any difference.

Nothing in the log file other than 'Starting C:\Program Files (x86)...' etc even though the service immediately stops but doesn't generate any other log entries!

Any ideas??

Chris

**Comment by oleg-nenashev** [comment]
Maybe your service user have no permission to see the folder, to which the instance points

**Comment by cjparsons** [comment]
Services runs under the local system account? I thought this had access to all the local resources on the server?

Chris

**Comment by oleg-nenashev** [comment]
@cjparsons It depends on how the service is configured. It may run under any account. The default account also depends on your Windows registry (but yes it's System by default)

Are there any other log entries?

**Comment by cjparsons** [comment]
No, the only entries in the log file are

<date> <time> - Starting C:\Program Files (x86)\...

The only way I can determine the issue was to look in the Windows Event logs...

I have tried to set the configuration file to run the service as me (I am an admin) but could not get the service to (re)install...

<serviceaccount>
  etc etc
</serviceaccount>

When I installed the service initially it was automatically installed running under the 'Local Service' account

I ought to mention it is running on Windows Server 2012 (which is new to me!)

I have also tried to change the login account from the 'Services' plugin and get the same issue.

This EXE is not designed to run as a windows services but apparently it is possible!

Chris

**Comment by cjparsons** [comment]
Think I may have made some progress - I set up a new service using the existing XML and CONFIG files pointing to Windows 'notepad.exe' and everything installed and ran correctly - including creating the <app>.out.log and <app>.err.log files I mentioned in my other message - running under the local system account, so it looks like the problem is running (some) other EXE files? 

...including the one I was looking at using 'winsw' for in the first instance :(

Chris

**Comment by oleg-nenashev** [comment]
Sorry, missed the updates. 
Hopefully WinSW 2 will provide more diagnostic capabilities.

**Comment by cash1981** [comment]
I have the same issue. Running with admin user on Windows Server 2012

First time I installed the service everything was ok. Then I updated the program, and changed the XML configuration and it didn't run.
Then I tried to reinstall, and now I get the following error:

```
System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at winsw.Util.ProcessHelper.StartProcessAndCallbackForExit(Process processToStart, String executable, String arguments, Dictionary`2 envVars, String workingDirectory, Nullable`1 priority, ProcessCompletionCallback callback)
   at winsw.WrapperService.StartProcess(Process processToStart, String arguments, String executable)
   at winsw.WrapperService.OnStart(String[] _)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)  at winsw.WrapperService.Main(String[] args)

```  

Whats strange is that I can run the exact same configuration on another server, and it works just fine.  I also tried providing full path to the file, but same error.

My configuration looks like this:
`<service>
  <id>agent-forbrukslaan</id>
  <name>agent-forbrukslaan-1-1</name>
  <description>Agen Forbrukslån. Cron jobb.</description>
  <env name="AGENT_BASIC_AUTH_PASSORD" value="9jxyfWHkjL"/>
  <env name="ORACLE_PROD_PASSORD" value="CFprod_admin01"/>
  <env name="LENDO_PASSORD" value="X7FJZ"/>
  <env name="AXO_PASSORD" value="Q93isKNYaX67gT8"/>
  <executable>C:\Program Files\Java\jdk1.8.0_112\bin\java</executable>
  <argument>-Dspring.profiles.active=prod,jobb</argument>
  <argument>-jar</argument>
  <argument>agent-forbrukslaan.jar</argument>
  <logpath>%BASE%\logs</logpath>
  <log mode="roll-by-size">
    <sizeThreshold>10240</sizeThreshold>
    <keepFiles>4</keepFiles>
  </log>
</service>`

**Comment by oleg-nenashev** [comment]
@cash1981 Are you sure your Java executable is located in `C:\Program Files\Java\jdk1.8.0_112\bin\java`? The error actually says it's not there or that the directory is not visible to the service account

**Comment by cash1981** [comment]
Yes. Wrong path to Java. Now I get access denied :)

**Comment by abhijeetcode** [comment]
I am getting below error, how can I resolve this issue.

`Service cannot be started. System.ComponentModel.Win32Exception: The system cannot find the path specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at winsw.Util.ProcessHelper.StartProcessAndCallbackForExit(Process processToStart, String executable, String arguments, Dictionary`2 envVars, String workingDirectory, Nullable`1 priority, ProcessCompletionCallback callback, Boolean redirectStdin, LogHandler logHandler)
   at winsw.WrapperService.StartProcess(Process processToStart, String arguments, String executable, LogHandler logHandler, Boolean redirectStdin)
   at winsw.WrapperService.OnStart(String[] _)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)`

Config file
`<configuration>
  <id>jmx-service</id>
  <name>JMX Service</name>
  <description>This service is a service gives the status of Local Atom</description>
  <executable>java</executable>
  <arguments>-jar %BASE%\jmx-service</arguments>
</configuration>`

**Comment by danawoodman** [comment]
Having the same issue here. If we use `C:\Windows\System32\notepad.exe` things work fine but if we try our executable at `C:\ourapp.exe` it fails. The app exists and has System/Administrator access and works on the command line. Any ideas @oleg-nenashev ?

**Comment by danawoodman** [comment]
Figured it on in our case; We were passing arguments to the `<executable>` section. Once we moved them to the `<arguments>` section, things worked as expected!

**Comment by NextTurn** [comment]
## How to obtain the full path to an executable using File Explorer

![image](https://user-images.githubusercontent.com/45985406/78215917-4b702a00-74eb-11ea-8e96-52970e4104a2.png)

## How to obtain the full path to an executable using PowerShell

```powershell
(Get-Item .\name.of.exe).FullName
```

I don't see any current action here so am closing this. Please file a new issue if further action is required. Thanks.

**Comment by deepakab03** [comment]
For me this error occurred if we specify the executable as just "java".  we need specify the full path to the java binary,then it worked. This occurs even if the %JAVA_HOME5/bin folder is part of the user PATH var

**Comment by kasp1** [comment]
Had the same problem trying to run the executable as a relative path. The absolute path had to be specified.

**Comment by duozhou** [comment]
> For me this error occurred if we specify the executable as just "java". we need specify the full path to the java binary,then it worked. This occurs even if the %JAVA_HOME5/bin folder is part of the user PATH var
的确是这样 我的java目录在 d盘 不在c盘   需要指定 D盘java的完整路径 才能运行起来jar包项目
