### ISSUE TITLE
No out and err log files?

### ISSUE THREAD

**Issue by cjparsons** [winsw/winsw#117]
I have just realised I am missing some log files - there is an <app>.wrapper.log file but no <app>.out.log or <app>.err.log ?

I set <logpath>(valid directory name)</logpath> ang <log mode="append"> sand restarted but nothing has appeared - I was a bit confused because the info on the intro screen mentioned <logmode>...</logmode>

Can't get the installed service to run so they may be created once it has started perhaps?

Regards

Chris

**Comment by roederja2** [comment]
The files only get created when output is written to these channels. Also there seems to be a rather long flush delay, so you may have to wait for quite a while until something actually shows up in the log file.

**Comment by oleg-nenashev** [comment]
Yes, files are created on the first write attempt. It could be changed if it it causes any concerns. Regarding the `flush()` operation, it depends on the copier threads. It could be adjusted as well

**Comment by NextTurn** [comment]
AFAICT there isn't really a flush delay in WinSW. Feel free to file a new issue if further action is required. Thanks.
