### ISSUE TITLE
File path issue

### ISSUE THREAD

**Issue by mia0x75** [winsw/winsw#119]
OS: Windows 10 x64

winsw.exe.conf:
`<configuration>
    <startup>
        <supportedRuntime version="v2.0.50727" />
        <supportedRuntime version="v4.0" />
    </startup>
    <runtime>
        <generatePublisherEvidence enabled="false" />
    </runtime>
</configuration>`

winsw.xml:
`<configuration>
    <id>nginx</id>
    <name>nginx</name>
    <description>High Performance Web Service</description>
    <executable>C:\Wnmp\nginx\nginx.exe</executable>
    <logpath>C:\Wnmp\nginx\logs\</logpath>
    <log mode="roll-by-size">
        <sizeThreshold>10240</sizeThreshold>
        <keepFiles>8</keepFiles>
    </log>
    <depend></depend>
    <startargument>-p C:\Wnmp\nginx</startargument>
    <stopargument>-p C:\Wnmp\nginx -s stop</stopargument>
</configuration>`

nginx version: 1.10.1

error log:
`nginx: [alert] could not open error log file: CreateFile() " C:\Wnmp\nginx/logs/error.log" failed (123: The filename, directory name, or volume label syntax is incorrect)
2016/07/12 10:35:03 [emerg] 716#5388: CreateFile() " C:\Wnmp\nginx/conf/nginx.conf" failed (123: The filename, directory name, or volume label syntax is incorrect)`

when I removed path argument (-p C:\Wnmp\nginx) from startargument and stopargument, the service can startup normally.

**Comment by oleg-nenashev** [comment]
Likely it's a nginx issue, because it receives the command line. I do not see what could be done on the WinSW side

**Comment by brkastner** [comment]
I was having the same problem when specifying `-p` and came across this issue. For future reference, you just need to split up your start/stop arguments. WinSW puts the entire argument into quotes which confuses nginx. 

`<startargument>-p C:\Wnmp\nginx</startargument>`
should be changed to
`<startargument>-p</startargument>`
`<startargument>C:\Wnmp\nginx</startargument>`

**Comment by harm-less** [comment]
Thanks @brkastner, after a few hours of searching, this was actually the solution which I would never have figured out on my own!

**Comment by oleg-nenashev** [comment]
Likely we need to patch the documentation then

**Comment by P0529** [comment]
you saved my life @brkastner

**Comment by monigala** [comment]
> I was having the same problem when specifying `-p` and came across this issue. For future reference, you just need to split up your start/stop arguments. WinSW puts the entire argument into quotes which confuses nginx.
> 
> `<startargument>-p C:\Wnmp\nginx</startargument>`
> should be changed to
> `<startargument>-p</startargument>`
> `<startargument>C:\Wnmp\nginx</startargument>`

@brkastner... this fixed it for me! Posting nginx version and nginxsvc.xml file.

![image](https://user-images.githubusercontent.com/9090923/60822069-9d04a780-a159-11e9-9fe9-843aae6c3374.png)

![image](https://user-images.githubusercontent.com/9090923/60822097-aaba2d00-a159-11e9-9057-e7d26e2655c0.png)

**Comment by NextTurn** [comment]
Please use \<argument**s**\>/\<startargument**s**\>/\<stopargument**s**\> (with an additional **s**).

**Comment by NextTurn** [comment]
\<argument\>/\<startargument\>/\<stopargument\> is designed for individual arguments.

\<argument**s**\>/\<startargument**s**\>/\<stopargument**s**\> is for multiple arguments. \<argument**s**\> is supported in all versions of WinSW. \<startargument**s**\>/\<stopargument**s**\> is supported since 2.9.0.

(I hope you can see this.)

**Comment by NextTurn** [comment]
Duplicate of #89
