### ISSUE TITLE
register service as local service and not system service

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [winsw/winsw#121]
I could not find a way to do that. I do not want to install the service as admin. I do not have the local user account info.

![image](https://cloud.githubusercontent.com/assets/20573460/18876458/6eeedeba-84e7-11e6-8af3-d2656ef5157c.png)

I want something like above. Is it possible ?

**Comment by oleg-nenashev** [comment]
It can be done via Windows service CLI or via Settings file. E.g. https://github.com/kohsuke/winsw/tree/winsw-2.0#service-account

**Comment by rahul-dutt-sharma** [comment]
<serviceaccount>
   <domain>YOURDOMAIN</domain>
   <user>useraccount</user>
   <password>Pa55w0rd</password>
   <allowservicelogon>true</allowservicelogon>
</serviceaccount>

waht do i set here .. I am trying 

 <serviceaccount>
        <domain>.\</domain>
        <user>LocalSystem</user>
        <password>""</password>
        <allowservicelogon>true</allowservicelogon>
    </serviceaccount>

**Comment by rahul-dutt-sharma** [comment]
I was able to register it with a different user but not as 'LOCAL SYSTEM' or 'LOCAL SERVICE'. Since I no longer need this for my current work please add this as a feature request if this is allowed by Windows.

**Comment by madargs** [comment]
If you don't specify a `<serviceAccount></serviceAccount>` it should default to the LocalSystem account. If you'd rather use LocalService or NetworkService, you would have to specify the domain as NT AUTHORITY.

**Comment by cournape** [comment]
FTR, I could only make it work by specifying `<domain>.\</domain>` when using a local account. For non windows experts, it would be useful to clarify this in the doc I think.

**Comment by oleg-nenashev** [comment]
Agreed regarding the `domain` setting. It should default to such value if not specified

Regarding the default account, I see no way of changing it without massive regressions. Though I agree it makes sense to consider it for 3.0

**Comment by kensykora** [comment]
This worked for me:

```xml
  <serviceaccount>
    <domain>NT AUTHORITY</domain>
    <user>LocalService</user>
  </serviceaccount>
```

**Comment by paulwarwicker** [comment]
@kensykora   Could you confirm which version you used when this succeeded. 

This would be my preferred configuration but if I use this I get the following error when installing the service: 

```
2018-03-10 19:01:33,833 FATAL - WMI Operation failure: StatusInvalidParameter
WMI.WmiException: StatusInvalidParameter
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServicesProxy.Create(String , String , String , ServiceType , ErrorControl , StartMode , Boolean , String , String , String[] )
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: StatusInvalidParameter
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServicesProxy.Create(String , String , String , ServiceType , ErrorControl , StartMode , Boolean , String , String , String[] )
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
```
I have the same issue if I use a local or domain account/password .

Thanks
-paul

**Comment by paulwarwicker** [comment]
Figured it out. It does not like the `<interactive />` element set.

-paul

**Comment by NextTurn** [comment]
> This worked for me:
> 
> ```xml
>   <serviceaccount>
>     <domain>NT AUTHORITY</domain>
>     <user>LocalService</user>
>   </serviceaccount>
> ```

https://github.com/winsw/winsw/issues/121#issuecomment-354882126 is the right solution to register a service as the `LocalService` account. It doesn't need a password. This will be documented.

> FTR, I could only make it work by specifying `<domain>.\</domain>` when using a local account. For non windows experts, it would be useful to clarify this in the doc I think.

This is a bug. It'll be fixed ASAP.

**Comment by NextTurn** [comment]
The `<domain>` now is optional and defaults to `.` (no backslash) i.e. the local computer.

**Comment by karlnicholas** [comment]
None of this stuff works for me. On Windows 11 Pro I can only run as my own user account.

**Comment by codewayer** [comment]
This is my config,it is works for me:
```
<serviceaccount>
    <domain>.\administrator</domain> 
    <allowservicelogon>true</allowservicelogon> 
  </serviceaccount>
```
