### ISSUE TITLE
Restart failing sometime

### ISSUE THREAD

**Issue by maurokade** [winsw/winsw#127]
Hi guys,
i´m using winsw to put my jar running in 20 clients.
i created a self update using the restart function, which worked perfect for me, and in staging with 5 clients.
But every production update, 3-8 clients fail when restart the app, it doesn't close the old jar before start the new one.
I worked in an alternative solution for that, instead of restart, i killed all java process using windows commands, winsw start the jar if it is not running, well, again it worked for me and staging, it failed in 10 clients when i deployed it to production. it killed the process and did nothing, i needed to ask the clients to restart manually the services to work.

anyone had this problem, any idea for solution?

**Comment by oleg-nenashev** [comment]
Could you please provide a WinSW configuration for your setup?

**Comment by maurokade** [comment]
`<service>
  <id>rr-valc-agent</id>
  <name>Rapid Reconciler 7 Agent</name>
  <description>Manages Rapid Reconciler services and updates</description>
  <env name="RRAGENT_HOME" value="%BASE%"/>
  <executable>%BASE%\..\jre\bin\java.exe</executable>
  <arguments>-jar "%BASE%\..\rr-valc-agent.jar"</arguments>
  <log mode="roll-by-time">
    <pattern>yyyyMMdd</pattern>
    
  </log>
  
  <onfailure action="restart" delay="10 sec" />
  <onfailure action="restart" delay="30 sec" />
</service>`

**Comment by calebboyd** [comment]
This might be related to #105, and #125

**Comment by oleg-nenashev** [comment]
@maurokade @calebboyd In WinSW 2.0 there were fixes around the process termination. In particular, #59, #159, and #124. There is also #125, which allows to automatically terminate runaway processes.

Please let me know if the new release solves the issue

**Comment by calebboyd** [comment]
Hi @oleg-nenashev. Thanks for all the work you put in. Will take a look as soon as we have the opportunity.

**Comment by maurokade** [comment]
thanks guys, i´ll change to winsw2.0 soon.

**Comment by oleg-nenashev** [comment]
@calebboyd @maurokade So, how does it work for you?
