### ISSUE TITLE
Error when start service

### ISSUE THREAD

**Issue by albertqhd** [winsw/winsw#163]
WMI.WMIException: ServiceRequestTimeout

details show on attachment.

Any suggestion?Thank you very much.    
![error](https://cloud.githubusercontent.com/assets/4747935/21178353/1a1f2cc0-c22a-11e6-8987-444d0bf74b33.jpg)

**Comment by oleg-nenashev** [comment]
It means the service process fails to start up, e.g. due to the missing log directory.
Could you please provide contents of your XML configuration fie?

Maybe it also makes sense to retry with the latest version, e.g. from here: https://github.com/kohsuke/winsw/releases/tag/winsw-draft-v2.0.3

**Comment by albertqhd** [comment]
The same server,winsw run well at beginning.Then I change it's ip address,switch to production environment,the error occurs.
Any suggestion?thank you

**Comment by oleg-nenashev** [comment]
@albertqhd Could you please answer my questions above?

**Comment by albertqhd** [comment]
<service>
  <id>apollo-DigitalBroker</id>
  <name>Apollo: DigitalBroker</name>
  <description>Apache Apollo is a reliable messaging broker</description>

  <logpath>D:\AP\DigitalBroker\log</logpath>
  <logmode>roll</logmode>

  <executable>"D:\AP\jdk1.7.0_80\jre\bin\java.exe"</executable>
  <argument>-server</argument>
  <argument>-Xrs</argument>
  <argument>-Xmx1G</argument>
  <argument>-Dcom.sun.management.jmxremote</argument>
  <argument>"-Djava.util.logging.config.file=D:\AP\apache-apollo-1.7.1\etc\jul.properties"</argument>
  <argument>"-Dapollo.base=D:\AP\DigitalBroker"</argument>
  <argument>"-Dapollo.home=D:\AP\apache-apollo-1.7.1"</argument>
  <argument>-classpath</argument>
  <argument>"D:\AP\DigitalBroker\etc;D:\AP\apache-apollo-1.7.1\lib\apollo-boot.jar"</argument>
  <argument>org.apache.activemq.apollo.boot.Apollo</argument>
  <argument>"D:\AP\DigitalBroker\lib;D:\AP\apache-apollo-1.7.1\lib"</argument>
  <argument>org.apache.activemq.apollo.cli.Apollo</argument>
  <argument>run</argument>

</service>

**Comment by albertqhd** [comment]
That's production server,so I can't just try another version.

**Comment by oleg-nenashev** [comment]
I do not see something wrong with the config. Maybe the application just takes too long to startup on the production due to whatever reason. You could try adjusting the service startup timeout: http://serverfault.com/questions/622432/how-do-i-increase-windows-service-startup-timeout

**Comment by albertqhd** [comment]
When error occurs,log file is not exists.I guess,the xml defined execution is not been execute.
May be something happend in winsw?

**Comment by oleg-nenashev** [comment]
> When error occurs,log file is not exists.

Log file is being created on the first write operation. Before it it may not exist. `wrapper.log` should exist by the time of the mentioned error.

If you still suspect WinSW and the proposed timeout settings do not work for you, please verify the issue on the new version (`2.0.1`) and report results
