### ISSUE TITLE
Process priority parameter - strange logic

### ISSUE THREAD

**Issue by oleg-nenashev** [winsw/winsw#169]
Service descriptor returns `null` priority if the setting is not specified
```
           var priority = _descriptor.Priority;
            if (priority != ProcessPriorityClass.Normal)
                processToStart.PriorityClass = priority;
```

So the actual behavior is:
- If the property is not specified, null is set. According to MSDN, it defaults to `Normal`
- If the property is `Normal`, PriorityClass is not assigned even if the initial priority was different
- Otherwise, the value is assigned

**Comment by pnikonowicz** [comment]
Has this been fixed here: https://github.com/kohsuke/winsw/blame/413e24ebebefc3cfbc80edacd16bf6f00a072450/src/Core/WinSWCore/ServiceDescriptor.cs
