### ISSUE TITLE
Stopping service has no effect

### ISSUE THREAD

**Issue by rsargant** [winsw/winsw#174]
I'm having recurring issues with WinSW 1.18 failing to SIGINT the service process when I stop the service from the control panel.  It seems to only happen if the service has been running without any issues for several weeks.

When I try to stop the service, it appears to immediately succeed (no visible wait/delay so I know it didn't work) and the service process (java.exe in this case) remains active. I then have to kill it manually from the task manager. I'm able to restart the service after that from the control panel without issue.

The log file doesn't show anything helpful.  Below is a relevant excerpt.

Failed Shutdown (runtime ~ 6 weeks)
2016-11-15 00:14:41 - Starting C:\Program Files\Java\jdk1.8.0_92\jre\bin\java.exe...
2016-11-15 00:14:41 - Started 1328
2016-12-27 23:59:54 - Stopping pCare
2016-12-27 23:59:55 - Finished pCare
2016-12-28 00:04:40 - Starting C:\Program Files\Java\jdk1.8.0_92\jre\bin\java.exe..
2016-12-28 00:04:40 - Started 13680
 
Normal Shutdown (runtime ~1 week)

2016-10-25 00:06:51 - Starting C:\Program Files\Java\jdk1.8.0_92\jre\bin\java.exe...
2016-10-25 00:06:51 - Started 588
2016-11-01 02:12:36 - Stopping pCare
2016-11-01 02:12:36 - ProcessKill 588
2016-11-01 02:12:37 - Stopping process 588
2016-11-01 02:12:37 - Send SIGINT 588
2016-11-01 02:12:54 - SIGINT to588 successful
2016-11-01 02:12:54 - Finished pCare

Config:
```
<service>
  <id>pCare</id>
  <name>TVRC-pCare</name>
  <description>pCare (Leviticus)</description>
  <executable>C:\Program Files\Java\jdk1.8.0_92\jre\bin\java.exe</executable>
   <arguments><!--omitted--></arguments>
    <workingdirectory>C:\TVRC\pCare</workingdirectory>
     <logpath>C:\TVRC\pCare\jetty\logs</logpath>
	<logmode>append</logmode>
	<stoptimeout>45sec</stoptimeout>
	<onfailure action="restart" delay="30 sec"/>
	<onfailure action="restart" delay="30 sec"/>
	<onfailure action="restart" delay="30 sec"/>
	<onfailure action="none"/>
	<resetfailure>5 min</resetfailure>
	<stopparentprocessfirst>true</stopparentprocessfirst>
</service>
```

Are there any known issues that might be causing this?

**Comment by oleg-nenashev** [comment]
According to the code "ProcessKill xxx" should be always printed if `Stoparguments` are null (it means there is no `stopargument` tag defined). Here is the code: https://github.com/kohsuke/winsw/blob/winsw-1.18/Main.cs#L288-L303

Are you sure the config is same for both runs?

**Comment by rsargant** [comment]
Thanks. Agree that "ProcessKill" should always be printed but in this case it definitely is not.

I've got no reason to suspect that the config is different between the runs.  I've also never fiddled with the <stopargument/> tag myself since I don't need to use an external shutdown application. 

I'm pretty sure that if I were to restart the service now (one day after last update), it would work fine. 
I will try that later and report back. 

I looked further back through the log . I can't find one example where the service was up for at least a month and this issue did NOT occur.  Nor can  I find one example where it was up for less then a month and DID occur.

Bizarre. Also difficult to see any possible explanation from the code .

**Comment by oleg-nenashev** [comment]
You can try the new SNAPSHOT build of WinSW (see GitHub Releases). the new releases improve overall logging in WinSW though I doubt it will help to catch this issue if it really happens somewhere. I can add more logging to the `stopexecutable` branch, so we may be able to at least confirm the fact the service goes to another branch of this code due to whatever reason

**Comment by oleg-nenashev** [comment]
@rsargant any updates?

**Comment by mrtechit** [comment]
Hi,

is there any update to this bug ?

**Comment by oleg-nenashev** [comment]
@mrtechit If you see this issue, please provide diagnostics info as requested above

**Comment by mrtechit** [comment]
@oleg-nenashev 
Hi, sorry but i opened a new issue below i came across this thread.

https://github.com/kohsuke/winsw/issues/262

Can you please check.

**Comment by mrtechit** [comment]
Hi,

I was able to reproduce this multiple times.

A temporary solution is to use the RunawayProcessKiller plugin.

However, what about the existing instance that is running before i include the RunawayProcessKiller in the configuration.

PS : I have an application deployed in production

Any suggestion ? :)

**Comment by mrtechit** [comment]
@oleg-nenashev Any advise ?
