### ISSUE TITLE
Deferred file operation not being executed

### ISSUE THREAD

**Issue by ArloL** [winsw/winsw#184]
I am currently trying to use winsw 2.0.1 on my Windows 8.1 Pro 64-bit. So far everything works really great. Thanks a lot. I have a small problem though with the deferred file operations. Sadly they are not executed. The file is deleted but nothing happens. This is my configuration together with a gif demonstrating that myapp.copies is deleted but dst ist not created.

myapp.xml
~~~
<configuration>
  <id>myapp</id>
  <name>MyApp Service (powered by WinSW)</name>
  <description>This service is a service cratead from a minimal configuration</description>
  <executable>ping</executable>
</configuration>
~~~

myapp.copies
~~~
src>dst
~~~

src
~~~
src
~~~

![winsw](https://cloud.githubusercontent.com/assets/195367/22286347/1e3f9f66-e2ef-11e6-836e-42911cca41e4.gif)

myapp.wrapper.log
~~~
2017-01-25 11:06:40,884 INFO  - Starting ServiceWrapper in the CLI mode
2017-01-25 11:06:41,142 INFO  - Starting ServiceWrapper in the service mode
2017-01-25 11:06:41,155 INFO  - Completed. Exit code is 0
2017-01-25 11:06:41,167 INFO  - Starting ping 
2017-01-25 11:06:41,171 INFO  - Starting ping 
2017-01-25 11:06:41,177 INFO  - Started 7060
~~~

Please let me know if you need more information.

**Comment by oleg-nenashev** [comment]
Hi. My apologies, missed the issue due to the vacation.
I will try to get Windows 8.1 and to test the use-case

**Comment by ArloL** [comment]
No worries. We all need some time off 👍

**Comment by dyorgio** [comment]
I'm trying to make an auto-update with deferred file feature, but no luck.
My copies file contains all files, but wrapper stops on my jar file.
I used rename approach to wrapper exe with success, another files were copied with success too.
In source(of wrapper) I couldn't find any problem, java -jar is only called after HandleCopies method, but for some reason it is not working (appears to be locked).
I already tried many approaches (restart!, stop/start, stop/start manual), always the same result.

**Comment by oleg-nenashev** [comment]
@dyorgio If you just want to auto-update the jar file, use the `download` option. If there is no runaway processes utilizing the JAR, it should work correctly. Otherwise https://github.com/kohsuke/winsw/blob/master/doc/extensions/runawayProcessKiller.md could help

**Comment by dyorgio** [comment]
Hi @oleg-nenashev!
Sadly my update is more complex that download option can handle, I really need a custom executable to do it.
In fact, I'm only using winsw for it (make a auto-update service to my software), my software is not a service.
I made many tests and alternative ways to kill/restart winsw and child process, how I said, no one could resolve the issue, not even manually.
It is a very strange issue, but my impressions is that winsw is open files before HandleCopy (however there is no evidence on source code) :(

**Comment by oleg-nenashev** [comment]
@dyorgio 
Sorry, missed the last comment. 

> It is a very strange issue, but my impressions is that winsw is open files before HandleCopy (however there is no evidence on source code) :(

When something goes weird, the first thing I suspect is the Antivirus. Sometimes it locks files from the deletion on the filesystem, though I would not expect it to happen regularly then. Seems I need  to finally get Windows 8.1 :(

**Comment by dyorgio** [comment]
@oleg-nenashev No problem man!
I'm using a Windows 10 VM to test my software on Micro$oft OS.
Windows Defender is the unique "antivirus" installed.

**Comment by dyorgio** [comment]
Hello, I check this today.
In fact, the deferred operation stops on winsw executable, not in my jar.
There is any limitation about it replaces itself?

**Comment by pareshvaniya** [comment]
Thanks @dyorgio - Just one last question - so as per my understanding, you are not using <download> tag of winsw, right?

**Comment by dyorgio** [comment]
Right.
I use last version in Releases page.
To clarify: I'm not using deferred file feature of winsw, I move files by myself using updater_helper.jar.

**Comment by pareshvaniya** [comment]
OK understand - you have created your custom logic of downloading & updating jar.
Thanks @dyorgio - It was nice talking with you.

**Comment by NextTurn** [comment]
https://github.com/winsw/winsw/blob/ea6ea9b2cc56d2244859d169f504bbe020527974/doc/deferredFileOperations.md#L14

A better way to support relative paths is to change the wrapper's working directory to the executable location but this would be a breaking change.

**Comment by NextTurn** [comment]
> In fact, the deferred operation stops on winsw executable, not in my jar.
> There is any limitation about it replaces itself?
> 
> Jenkins appears to handle it in a special way...:
> https://github.com/kohsuke/jenkins/blob/master/core/src/main/java/hudson/lifecycle/WindowsServiceLifecycle.java#L78

Windows does not allow replacing running executable files. The "delayed replacement" method you mentioned is valid. Another approach is to move the old executable away and then place the new one, which is used by the Windows Agent Installer for Jenkins (#399).

---

Periodic updates are not supported so far. Feel free to send a feature request.

---

Relative paths are supported in 3.x.
