### ISSUE TITLE
Status command text contains log output

### ISSUE THREAD

**Issue by Digital-Chaos** [winsw/winsw#206]
$ winsw status
The above command now emits INFO logging text in addition to the expected service status string due to ConsoleLogger being enabled if in "cli mode" (which seems to be if you have args > 0)??? There also seems no way to disable this logging from the configuration?

**Comment by oleg-nenashev** [comment]
Not for now. https://github.com/kohsuke/winsw/issues/158 should add support of it.

BTW I doubt that "status" command will ever guarantee to provide a short output since there is some long-term plan to have more diagnostics there. What is your use-case? Is it for monitoring?

**Comment by Digital-Chaos** [comment]
The current docs on the front page say that the status command will return one line which indicates the status of the service with values of "NonExistant", "Started", or "Stopped", which is no longer true. 

Our use case is that we have automated deployment of a Spring Boot app in which we have an initial powershell step which checks the state of the service (utilizing the result of the winsw status command) and then stops it if running. There is also a final step after deployment to check for the existance of the service (again using winsw status) and install it if necessary and then start the service. 

Why change the exisitng "status" command to add extra diagnostics output and potentially cause breakage for existing users when you could add an additional command such as "winsw diagnotics" or something similiar and avoid breaking anything?

**Comment by oleg-nenashev** [comment]
If it is documented, I agree it should behave in the described way. Adding it to the 2.2 scope

**Comment by Digital-Chaos** [comment]
Much appreciated, and thank you for your time and effort maintaining this project! :-)

**Comment by oleg-nenashev** [comment]
Released in 2.1.1.
Sorry for the delay. I should spend more time on establishing Continuous Delivery in my projects :(

**Comment by oleg-nenashev** [comment]
Looks to be completed, the command works well on the current version. Please feel free to reopen if I missed anything
