### ISSUE TITLE
Can't start service - WMI Operation failure: AccessDenied

### ISSUE THREAD

**Issue by sukinsky** [winsw/winsw#210]
Hello!
Having problems with actual version on Windows 2012 R2.
Successfully installed service for nginx.exe with default minimal config. Starts with SYSTEM account.

If I start service (under administrator rights) with "net start" I got:
`System error 5 has occurred.
Access is denied.`

If I start service with "WinSW.NET4.exe start" I got:
`2017-04-21 11:35:01,236 INFO  - Starting ServiceWrapper in the CLI mode
2017-04-21 11:35:01,518 FATAL - WMI Operation failure: AccessDenied
WMI.WmiException: AccessDenied
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
`
Thanks,
sukinsky

**Comment by oleg-nenashev** [comment]
In order to start services from CLI, it is not enough to be a system administrator. Or command shall should be started with "Run as Administrator" privilege.

**Comment by sukinsky** [comment]
Of course I start CMD with "Run as Administrator" privilege. The same error is from Services or Task manager.

**Comment by oleg-nenashev** [comment]
Hm, maybe there are some restrictions for service management in your Windows (e.g. Domain policy). Just to make sure, are you able to manage other services?

**Comment by sukinsky** [comment]
Yes I'm inside enterprise environment with domain and local admin on target computer. I'm able to manage any service installed, I can install own services (may be you know `nssm.exe`).

I used `winsw` on WS2008R2 in same environment without any problems.
Tried add ".NET Framework 3.5 Features", checked that WMI service is running.

**Comment by sukinsky** [comment]
Hi, Oleg!

Old version (2.0.0) it works as a charm. After I tried downgraded version - all versions of winsw began to work. I think there were some local PC issues.

**Comment by Ishan1987** [comment]
HI @sukinsky ,

I had the similar issue that i fixed with below 2 steps:
1) Added user in to admin group
2) goto your downloaded jenkins-slave.exe Application file.
goto properties -> compatibility -.> check run as administrator
Then i retried installing jenkins as service resolved the issue. Make sure to click ok on prompt where service will be run as admin.

**Comment by ricklefort** [comment]
I'm getting the same access denied error on Windows 2012 R2.  

I tried the last suggestion from Ishan1987 but that didn't work for me.  I'm assuming the "jenkins-slave.exe" is winsw renamed?

I also tried using winsw-v2.1.2, but got the same error.

Help, any ideas?

**Comment by mariafleetwood** [comment]
I have Windows server 2016 and had the same problem with permissions(even I have admin rights on this server).
I solving it by similar instructions 

- Create node with Remote root directory: C:\agents\agent_xx
- Lunch node via web
- Attempt to install as service via web (this part is failing but it generate jenkins-slave.exe in C:\agents\agent_xx\ folder)
- Open command prompt as admin
- `sc.exe create Jenkins_agent_xx binPath= "C:\agents\agent_xx\jenkins-slave.exe"`
- Close windows where you lunch node, to take node offline
- Go to services and change the properties (I would recommend change loging details to the same user as run jenkins and run services automatically)
-  Start service and enjoy :-)

**Comment by kalakhr** [comment]
Check the permissions on the executable file itself.  From explorer right click on the exe file 
-> Properties -> Security 
Check the "Group or user names" and make sure that you have the right permissions on the file.

**Comment by tharindus92** [comment]
> HI @sukinsky ,
> 
> I had the similar issue that i fixed with below 2 steps:
> 
> 1. Added user in to admin group
> 2. goto your downloaded jenkins-slave.exe Application file.
>    goto properties -> compatibility -.> check run as administrator
>    Then i retried installing jenkins as service resolved the issue. Make sure to click ok on prompt where service will be run as admin.

thanks Its work...

**Comment by NextTurn** [comment]
WinSW will prompt for UAC in non-elevated sessions in the next version (2.8). **None of the above workarounds are longer needed.**

Feel free to file a new issue if further action is required. Thanks.
