### ISSUE TITLE
Create chat in Gitter/whatever?

### ISSUE THREAD

**Issue by oleg-nenashev** [winsw/winsw#211]
I am not sure if the chat is really required for this project, but I am ready to create it if somebody would like this communication approach. Just cast your votes in this issue

**Comment by oleg-nenashev** [comment]
@NextTurn what is your preference about communication channels for WinSW? Would you like to have a separate chat for that?

**Comment by NextTurn** [comment]
@oleg-nenashev It would be good to have a Gitter room as an async channel.
