### ISSUE TITLE
Use Stop Executable without arguments

### ISSUE THREAD

**Issue by pnikonowicz** [winsw/winsw#216]
Even though this is the documented behavior, it would be nice to be able to call the stop executable without passing in arguments. 

This can be done be manipulating the code here:
https://github.com/kohsuke/winsw/blob/7be52c79e4bde53c2d6e92cd4923e95c50264986/src/Core/ServiceWrapper/Main.cs#L298

**Comment by oleg-nenashev** [comment]
IIRC I just documented the existing behavior, which didn't seem to be perfect. I agree it worth changing it
