### ISSUE TITLE
writing to stdout from a stopexecutable will eventually cause the process to hang

### ISSUE THREAD

**Issue by pnikonowicz** [winsw/winsw#218]
This happens because the stop executable's stdout stream is redirected to the parent process but is never drained, thus eventually causing the stopexecutable's stdout writer to hang. 

I recommend either setting these flags to false here:
https://github.com/kohsuke/winsw/blob/0da384180419ae5557685736e1e0e5fdab17eeff/src/Core/WinSWCore/Util/ProcessHelper.cs#L141

Or actually consuming the processes stream and piping it to a log file. 

For more info on how to redirect stdout from a process, see here:
https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.redirectstandardoutput(v=vs.110).aspx

**Comment by oleg-nenashev** [comment]
> Or actually consuming the processes stream and piping it to a log file

This one sounds like a plan

**Comment by oleg-nenashev** [comment]
The change also impacts the start (common) executable. According to the brief testing it is not correct in that case because the logs are being drained correctly there to logfiles. I will revisit the implementation, hopefully within 1-2 days

**Comment by oleg-nenashev** [comment]
The fix has been released in 2.1.1
Once I get #213 integrated, I will setup forwarding of the output to the wrapper log
