### ISSUE TITLE
how to prevent event log entries?

### ISSUE THREAD

**Issue by daeks** [winsw/winsw#241]
I havent found an answer in the docu. Is there a way to prevent that wsw is writing to eventlog?

**Comment by daeks** [comment]
I have created a wrapper instance called test.exe but as soon as I am starting it, I found a lot of these messages in the application log:

The description for Event ID 2 from source Squad-PID2596 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

**Comment by oleg-nenashev** [comment]
#213 should make Logging configurable, and you can disable the most of event logging there. Something explicit like #158 could be a better fix though

**Comment by daeks** [comment]
thanks for the hint - how does the config needs to look like? I want the same log in the logdirectory as it is now, but just want to disable the spam in the eventlog (~15 rows / second)

**Comment by oleg-nenashev** [comment]
@daeks sorry, missed the comment. There is some documentation missing, will update the PR by tomorrow

**Comment by NextTurn** [comment]
> The description for Event ID 2 from source Squad-PID2596 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

This bug has been fixed since 2.0.
