### ISSUE TITLE
View stdout and stderr in the logs

### ISSUE THREAD

**Issue by wayofthefuture** [winsw/winsw#242]
Anyone know how to view the output of the service process in the logs? Looking to see stdout and stderr.

Thanks.

**Comment by oleg-nenashev** [comment]
WinSW writes these logs by default to the disk. `${executable.name}.err.log` and `${executable.name}.out.log`

**Comment by wayofthefuture** [comment]
Hmmmm... for some reason I only see "exectuable.name.wrapper"

I have logging setup to roll-by-time. I have checked in the log folder and the executable folder. Would it be elsewheres?

**Comment by oleg-nenashev** [comment]
My bad, logs are not being written to the disk by default. You need to specify logmode, e.g.

```
  <logmode>rotate</logmode>
```

**Comment by oleg-nenashev** [comment]
Once I finalize https://github.com/kohsuke/winsw/pull/213, I'll probably add executable log forwarding to STDOUT by default

**Comment by wayofthefuture** [comment]
I may be misunderstanding. I have a logmode setup in my xml. It is set to roll-by-time.

``` xml
<log mode="roll-by-time">
  	<pattern>yyyy-MM-dd</pattern>
</log>
```

Unfortunately I don't see any logging though. I'm looking to see the stdout of the target process the service executable references inside the <executable> tag.

**Comment by steve-bate** [comment]
I had the same issue. My relative log directory path was being resolved
with c:\windows\system32 as the base directory. I found my log files there. Using an absolute log directory path fixed the issue for me.

**Comment by nchevsky** [comment]
> I have `<logpath>` set, but the logs are going to C:\windows\system32 for me too. Is there anyway to have the stdout and stderr logs go to a relative directory via `<logpath>`?

Prepend `%BASE%\` to your relative path.
