### ISSUE TITLE
Roll by time and size

### ISSUE THREAD

**Issue by DHirani** [winsw/winsw#243]
Is possible if my logs can roll by date and time and by size and to keep the latest the same name?

E.g.
MainApp.log
MainApp2017-08-15.#0001.log
MainApp2017-08-15.#0002.log
MainApp2017-08-15.#0003.log
MainApp2017-08-14.#0001.log
MainApp2017-08-13.#0001.log
MainApp2017-08-12.#0001.log

Then can the older ones be zipped up based on their age, can the zip file be controlled by month.
E.g.
MainApp.2017-07.zip
MainApp.2017-06.zip

Kind regards,

Buddy

**Comment by DHirani** [comment]
I've added support for this.

**Comment by jdziat** [comment]
It looks like this feature may be broken at least according to the documentation.
