### ISSUE TITLE
err.log not available when using custom path or log-roll mode

### ISSUE THREAD

**Issue by RovoMe** [winsw/winsw#244]
I have a tiny Spring-Boot application which I start via winsw-2.1.2 as a service using the sample below:

    <service>
        <id>service</id>
        <name>Service Name</name>
        <description>Some description</description>

        <workingdirectory>%BASE%/..</workingdirectory>
        <onfailure action="restart" delay="10 sec"/>
        <stopparentprocessfirst>true</stopparentprocessfirst>
	
        	
        <executable>java</executable>
        <arguments>-Dspring.profiles.active=prod -Dloader.path="conf/*" -jar "bin/service.jar"</arguments>

        <logpath>../logs</logpath>
        <log mode="append"/>
        
        
    </service>

If I define `log mode="append"` (or do not define it at all) I see a *.err.log, *.out.log and *.wrapper.log in the same directory as the executable as long as I do not define any custom `logpath` expressions. Also, I'd like to use rolling log files though here also only the wrapper.log will be rolled and no err.log or out.log are visible. 

Is there a way to generate error/out logs in the specified log directory as well?

**Comment by oleg-nenashev** [comment]
https://github.com/kohsuke/winsw/pull/213 is going to be a silver bullet for all logging cases

**Comment by oleg-nenashev** [comment]
You could try it and provide feedback if it solves your case
