### ISSUE TITLE
WinSW 2 and 4 error "0xc000007b" on start

### ISSUE THREAD

**Issue by betonetotbo** [winsw/winsw#264]
I'm trying to use WinSW on a Windows 7 x64 Ultimate. 

After installing .Net Framework 2.0 and 4.7 I still getting the error 0xc000007b.

Any ideia how to solve it ?

**Comment by oleg-nenashev** [comment]
Could you please provide the full log?

**Comment by NextTurn** [comment]
`STATUS_INVALID_IMAGE_FORMAT` is a general error not specific to the product. I can only suggest you try the new native binaries or try performing some system fixes or reinstalling .NET Framework or even the OS and so on.
