### ISSUE TITLE
<depend> is not properly working??

### ISSUE THREAD

**Issue by phanigandeed** [winsw/winsw#269]
In my project, I have a dependency specification like this.
      <executable>java</executable>
      <arguments>-Xrs -Xmx256m -jar "%BASE%\demoservice.jar"</arguments>
      <depend>demoservice2</depend>
      <logmode>rotate</logmode>
    </service>
....

And, I have installed both demoservice, and demoservice2.

But, even if demoservice2 is not running, demoservice is running. As per specification in your documentation, it should not run.

Is my understanding wrong?

**Comment by oleg-nenashev** [comment]
Hello, WinSW just declares dependencies when it installs the service. All management happens on the Windows side

* Which WinSW version do you use?
* What is your operating system?
* Please provide a registry dump for both installed services

**Comment by NextTurn** [comment]
`<depend>` is working properly as of the latest version.

It's possible that the dependency service crashes when running. In that case the dependent services won't automatically stop.
