### ISSUE TITLE
Process not being killed after stopexecutable failed

### ISSUE THREAD

**Issue by TLDC** [winsw/winsw#270]
I have a winsw service which has a separate stopexecutable defined which calls some logic to close the original executable down gracefully.

Unfortunately, there are some circumstances outside of my control in which the shutdown logic might fail and if it does the service gets stuck in the state 'Stopping' and the original process seems to never get killed even after defining a `<stoptimeout>`

**Comment by oleg-nenashev** [comment]
As designed IMHO. If a user defines a `stopexecutable`, it means that the standard termination logic is not doing what the user expects. So killing the process may cause collateral damage on the application.

I am happy to discuss options like optional flags, but I do not consider it as a defect

**Comment by TLDC** [comment]
Thanks for the quick response. That is a good point and I thought this might be the case.

I would find an optional flag for timing out with a stopexecutable extremely useful if it is possible!

**Comment by NextTurn** [comment]
This is actually a bug. The current logic expects both to exit but a bug in the implementation exits the wrapper right after the stopexecutable exits.
