### ISSUE TITLE
Nginx depends on PHP

### ISSUE THREAD

**Issue by sistematico** [winsw/winsw#273]
I have this service:
``<service>  
	  <id>nginxsvc</id>  
	  <name>Nginx</name>  
	  <description>Nginx Web Server service.</description>  
	  <workingdirectory>C:\nginx</workingdirectory>  
	  <executable>nginx</executable>  
	  <depend>phpsvc</depend>  
  </service>``

and

``<service>  
	<id>phpsvc</id>  
	<name>PHP</name>  
	<description>PHP FastCGI service.</description>  
	<workingdirectory>C:\php</workingdirectory>  
	<executable>php-cgi</executable>  
	<arguments>-b 127.0.0.1:9123 -c "C:\php\php.ini"</arguments>  
</service>``

And this error:

``C:\svc\nginx>nginxsvc.exe start  
  2018-04-14 06:06:06,197 INFO  - Starting the service with id 'nginxsvc'  
  2018-04-14 06:06:06,213 FATAL - WMI Operation failure: ServiceDependencyDeleted  
  WMI.WmiException: ServiceDependencyDeleted  
     em WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)  
     em WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)  
     em WMI.Win32ServiceProxy.StartService()  
     em winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)  
     em winsw.WrapperService.Main(String[] args)  
  WMI.WmiException: ServiceDependencyDeleted  
     em WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)  
     em WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)  
     em WMI.Win32ServiceProxy.StartService()  
     em winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)  
     em winsw.WrapperService.Main(String[] args)``

**Comment by oleg-nenashev** [comment]
Is `phpsvc` installed, just to make sure? Do you use system-wide services or per-user ones?

**Comment by sistematico** [comment]
nvm, fixed: https://gist.github.com/sistematico/d84e04bbd7eec65dc35a76b634726887

Thank you!
