### ISSUE TITLE
Silencing Application event log entries?

### ISSUE THREAD

**Issue by theultramage** [winsw/winsw#278]
Everytime the service starts and stops, it writes multiple entries into the Application event log, including the full commandline, twice, and a warning about a SIGINT timeout. This adds a lot of pointless noise into the log. Is there a way to disable this logging?

**Comment by theultramage** [comment]
````<log mode="none"/>```` is present in my configuration file, that's why I submitted this issue. Somehow I forgot to include this fact.

**Comment by oleg-nenashev** [comment]
`log mode="none"` addresses only logging to the disk, but it does not impact event logs in the legacy code within WinSW. #213 is probably a solution, assuming I ever got it over the fence (hope so)

**Comment by NextTurn** [comment]
Duplicate of #241
