### ISSUE TITLE
Support "If-Modified-Since" header for HTTP(s) resources

### ISSUE THREAD

**Issue by kvach2avl** [winsw/winsw#279]
Hi!
It will be great to support last date modification checking for resources of the self-updating services. For HTTP(s) resources it's possible to set "If-Modified-Since" header constructed from the modification date/time of an already downloaded resource and further checking of HTTP reply for 304 code.
This will be very helpfull for large resources uploaded by service on slow Internet connections.

**Comment by NextTurn** [comment]
Implemented in #403
