### ISSUE TITLE
Service goes into sleep mode

### ISSUE THREAD

**Issue by GarbageYard** [winsw/winsw#287]
Hello,

I created Windows service for a Java application (JAR). It worked fine but the problem is that whenever another service tries to hit this Windows service for the first time, it throws 500 error. On subsequent hits, it works fine. Again, if after some time, some service tries to hit this Windows service, it throws 500 error and then on subsequent hits, works fine. Seems like the Windows service goes into sleep mode.

I have created a bat file which is invoked by configuration file (XML). All three (EXE, XML and BAT) are in the same dir.

BAT file (my-app.bat) content:
```
@echo off
IF %3==dev (net use R: %1) ELSE (net use P: %1)
net use T: %2
java -jar -Dspring.profiles.active=%3 "../my_app.jar"
```

XML file (my-app.xml) content:
```
<?xml version="1.0" encoding="UTF-8"?>
<service>
    <id>my-app</id>
    <name>My App</name>
    <description>My App Windows Service</description>
    <executable>my-app.bat</executable>
    <argument>%P_DRIVE%</argument>
    <argument>%T_DRIVE%</argument>
    <argument>%ENV_NAME%</argument>
    <logpath>../logs/</logpath>
    <logmode>rotate</logmode>
</service>
```
Any idea why this might be happening?

**Comment by oleg-nenashev** [comment]
Is error 500 being thrown by your *web* service? Afaik there is no code in
WinSW which may throw it.

I have seen similar issue with the entire Windows VM going to sleep. I
would recommend checking system logs. If it does not help, I recommend to
get and analyze the error message and stacktrace from the service side.

**Comment by GarbageYard** [comment]
Thanks for the inputs but what i want to also highlight here is that prior to running it as Windows service, it was running just fine. I disabled the service today after this issue came up again. Now when it's running on command prompt (Administrator mode), it's running just fine. The user with which it was running as Windows service is also having admin privileges.

**Comment by oleg-nenashev** [comment]
Thanks for the insights. Unfortunately, the report cannot be diagnosed
without  system logs, stacktraces or step-by-step reproduction guides.
Please provide them.

**Comment by NextTurn** [comment]
Windows services do not automatically prevent the system from sleeping. Why not simply adjust the power options?
