### ISSUE TITLE
download : Received an unexpected EOF or 0 bytes from the transport stream.

### ISSUE THREAD

**Issue by philippe-granet** [winsw/winsw#288]
When i add this to configuration:
`<download from="https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.121.2/jenkins-war-2.121.2.war" to="%BASE%\jenkins.war" auth="sspi" failOnError="true"/>`  

I have this error:

> 
> 2018-08-05 16:35:23,950 ERROR - Failed to download https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.121.2/jenkins-war-2.121.2.war to ...\jenkins.war
> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException The exception message is: Received an unexpected EOF or 0 bytes from the transport stream.
>    at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
>    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.ConnectStream.WriteHeaders(Boolean async)
>    at System.Net.HttpWebRequest.GetResponse()
>    at winsw.Download.Perform()
>    at winsw.WrapperService.OnStart(String[] _)
>

**Comment by oleg-nenashev** [comment]
Sorry, I missed this ticket. Likely it is caused by `sspi` authentication which cannot really work against the Jenkins repo. I also advice to download Jenkins from download mirrors, not from Artifactory directly

**Comment by pareshvaniya** [comment]
Hi @kohsuke @oleg-nenashev  - I am searching for windows service auto update as my service installed in around 1000 different client servers and found below link for download <Tag> :
[](https://github.com/kohsuke/winsw/blob/master/doc/xmlConfigFile.md#download)
> This is another useful building block for developing a self-updating service.
So how can we do auto update of jar using this same download tag ?

**Comment by NextTurn** [comment]
I just tried the same setting and it worked well. The issue description didn't indicate that it was caused by the authentication, right?

@pareshvaniya You need a link that always points to the latest version of jar, like the [latest release](https://github.com/winsw/winsw/releases/latest).
