### ISSUE TITLE
Nginx, which uses a custom configuration file to set up windows boot self-boot service, found that stopargument of XML file is not valid

### ISSUE THREAD

**Issue by janzz11** [winsw/winsw#291]
Hello,
I want to implement nginx's custom boot-up self-service, but there are always cases where the service can't stop. I don't know how to pass parameters to nginx's stop command, just as I want to implement E: nginx-1.12.2 nginx.exe -p E: nginx-1.12.2 -c  conf nginx-8161-web.conf start nginx and E:\ nginx-1.12.2\ nginx nginx. .exe -c \conf\nginx-8161-web.conf -s stop stops nginx

How can I write a configuration file without making mistakes?

The following is the configuration file I wrote.
[nginx-8161-web.txt](https://github.com/kohsuke/winsw/files/2330592/nginx-8161-web.txt)

Please help

**Comment by waterdeng** [comment]
`<stopargument>-p %WHATEVER%\nginx-1.15.6\ -s stop</stopargument>`

**Comment by laguiz** [comment]
May help 
```
<service>
  <id>nginx</id>
  <name>nginx</name>
  <description>nginx</description>
  <executable>D:/nginx/nginx/nginx.exe</executable>
  <logpath>D:/nginx</logpath>
  <logmode>roll</logmode>
  <depend></depend>
  
  <startargument>-p</startargument>
  <startargument>D:/nginx/nginx</startargument>
  
  <stopargument>-p</stopargument>
  <stopargument>D:/nginx/nginx</stopargument>
  <stopargument>-s</stopargument>
  <stopargument>stop</stopargument>
  
</service>
```

**Comment by TanqiZhou** [comment]
666
