### ISSUE TITLE
serviceaccount password on command line

### ISSUE THREAD

**Issue by arthurblake** [winsw/winsw#30]
I am struggling with the security problems of passing logon credentials in clear text in the xml (under serviceaccount element) and would prefer a way to pass the credentials directly on the command line... (when installing service.)

I saw that issue #19 may address this, but cannot find exact usage information on that. Could you document basic usage of that feature?

**Comment by oleg-nenashev** [comment]
I think it's actually and still reasonable for some cases

**Comment by waffel** [comment]
Interesting. I had also searched for a option to give the login password for the service accont on cmd while installing the service. /p helped me out (but also asked for username and logon behaviour).

It would be nice to have this information in the install guide (or how to get those "hidden" flags on cmd /? or --help does not print out the option).

**Comment by vsspt** [comment]
Can you please inform me what is the state of this issue?
Is this implemented in the 2.X version?

**Comment by NextTurn** [comment]
The `/p` argument was added in 1.14 and documented (only) in the installation guide since 2.0.

https://github.com/winsw/winsw/blob/ea6cb8062aa0c2479cbbaec107bdb6050b110f1a/doc/installation.md#L54-L55

Bear in mind that `/p` reads password from the keyboard, not from STDIN. 

More arguments can be implemented as part of #433.

**Comment by HackerBaloo** [comment]
I did't like the /p option, I made a little workaround, by writing the service config twice, first one time with password, I use that for installing the service, then I let my installer write the config file again without the password. It works fine for start, stop, status and uninstall

**Comment by waffel** [comment]
@HackerBaloo I have done the same. 

The ugly thing about this solution: You really should ensure to not leave the password for the service account in the configuration file. Then a "hacker" or ugly user can read the password of your service account. 
We have managed to get rid of this by limiting read access to the files ... but all of this is a workaround just to not be able to provide the password on install per command line parameter. So for an "automatic" and easy way of installing services, a command-line switch would be helpful.

**Comment by billbarni** [comment]
I'm having this problem today. When delivering a package I have to make sure to remove the xml file or limit read, or some other absurd stuff. I can't have a password in text laying around. 
Please, just give us the ability to use CLI to do everything.

**Comment by billbarni** [comment]
The only thing holding me back in using the 'dev' version, is it's release in Maven/Jenkings Repo.
