### ISSUE TITLE
not support windows server 2019

### ISSUE THREAD

**Issue by xjl456852** [winsw/winsw#300]
When i add a service and start it.  it prompts an error message,see image

https://ibb.co/FDpP9gn

**Comment by oleg-nenashev** [comment]
Thanks for the report! Please provide screenshots in english, I cannot read Chinese

**Comment by oleg-nenashev** [comment]
OK, I will need a WinSW log. A full event log dump could also help. There is no information for diagnostics in the provided screenshots

**Comment by m8urnett** [comment]
I am seeing the same issue. Running procmon it looks like the child executable never runs. There is no indication of any other error in the eventlogs or in procmon. 

Here is the log output:
```
2019-03-03 17:52:52,838 INFO  - Starting ServiceWrapper in the service mode
2019-03-03 17:52:52,872 INFO  - Starting "C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe"  
2019-03-03 17:52:52,876 INFO  - Starting "C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe"  
2019-03-03 17:52:52,893 DEBUG - Completed. Exit code is 0
```

**Comment by bnflix** [comment]
@oleg-nenashev I have narrowed this down some, I found that versions 2.1.2 and earlier work fine in Windows Server 2019.

**Comment by m8urnett** [comment]
I have narrowed this down some. It seems versions 2.1.2 and earlier work and it also seems to work in the latest version if I remove the <workingdirectory> element.

**Comment by coolemg** [comment]
I used the winsw-2.2.0-net4.exe. It couldn't run well on windows server 2019.
Here is windows event log.

Service cannot be started. System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at winsw.Util.ProcessHelper.StartProcessAndCallbackForExit(Process processToStart, String executable, String arguments, Dictionary`2 envVars, String workingDirectory, Nullable`1 priority, ProcessCompletionCallback callback, Boolean redirectStdin, LogHandler logHandler)
   at winsw.WrapperService.StartProcess(Process processToStart, String arguments, String executable, LogHandler logHandler, Boolean redirectStdin)
   at winsw.WrapperService.OnStart(String[] _)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

**Comment by brindhar90** [comment]
I am using winsw-2.2.0-net4.exe and it works fine in my local windows 10 machine. The same setup isn't working in Windows server 2008/12. The process is not getting started as it did in my local.

2019-07-31 11:55:02,509 INFO  - Starting the service with id 'TestService'
2019-07-31 11:55:02,721 INFO  - Starting ServiceWrapper in the service mode
2019-07-31 11:55:02,751 DEBUG - Completed. Exit code is 0
2019-07-31 11:55:02,799 INFO  - Starting java -jar "E:\Program Files\TestService\TestService-1.0.0-SNAPSHOT.jar"
2019-07-31 11:55:02,804 INFO  - Starting java -jar "E:\Program Files\TestService\TestService-1.0.0-SNAPSHOT.jar"
2019-07-31 11:55:02,834 DEBUG - Completed. Exit code is 0

**Comment by brindhar90** [comment]
I found the solution in your other forum. The executable path was the issue. After adding the java executable  is System path, the process started just fine. Thanks!

**Comment by bhadouriyanikhils** [comment]
I am having the same problem whenever I try to start the service it starts then stops with this error 1067. 
**_Details:_** I have placed all the .exe, .xml, .jar in the same directory(on windows machine which is in company's network)
**Below is the data coming out in appName.err.log file:**

Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -j9vm	  to select the "j9vm" VM
                  The default VM is j9vm.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.``

**Below is my app's XML file data:**

<service>
  <id>appName</id>
  <name>appName</name>
  <description>appName Spring Boot App</description>
  <startmode>Automatic</startmode>
  <executable>C:\Program Files\AdoptOpenJDK\jdk-8.0.202.08\bin\java.exe</executable>
  <executable>-jar %BASE%\appName.jar</executable>
</service>

Using WinSW.NET461 on windows 10(Oct 2019) and .Net framework version is 4.8.
I am executing the install, start commands on powershell command window as an admin.
Can someone please help what could be the issue?
![WindowsServiceIssue](https://user-images.githubusercontent.com/59281197/79234015-3f8b4d00-7e87-11ea-98f7-bef0ee013c2a.PNG)

**Comment by NextTurn** [comment]
@bhadouriyanikhils You placed the arguments in an `<executable>` element. They should be places in `<argument>` or `<arguments>`.

**Comment by bhadouriyanikhils** [comment]
@NextTurn, Thanks a lot for your quick help!
I rectified the mistake and the service is up and running fine.

**Comment by NextTurn** [comment]
Good to hear that @bhadouriyanikhils! You've made an awesome example of providing valuable feedback.

**Comment by NextTurn** [comment]
For whoever experiencing this problem:

- Please provide your XML configuration for diagnosis.
- Please make sure you didn't place arguments in `<executable>`.
- Please make sure you didn't place multiple arguments in `<argument>`.

Thank you for understanding.

**Comment by NextTurn** [comment]
@xjl456852 Could you please explain the `?` character after the `-c` argument?

See #333 for the suspected cause (and why I request you to provide the XML).
