### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by NiekBaer** [winsw/winsw#304]
Hey guys,

Not sure if this is caused by our software or the wrapper. We experience that when we close the java services with the wrapper, that occasionally the java instance isn't killed properly. Then, when we start up the service again, the error message "java.net.BindException: Address already in use" pops up. We know that this means that there is still a java instance running at the port, and we know how to kill it manually. What we would like to know if it is possible to prevent this from happening at all. Why is this happening? Could it be caused by the wrapper?

Help would be really appreciated!

Best regards,
Niek

**Comment by oleg-nenashev** [comment]
Sorry, I missed that. [Runaway Process Killer](https://github.com/winsw/winsw/blob/master/doc/extensions/runawayProcessKiller.md) could help, usually such issues are caused by improper termination. With #440 it should become a default behavior
