### ISSUE TITLE
PowerShell environment variables not honoured  

### ISSUE THREAD

**Issue by MaRuifeng** [winsw/winsw#305]
Though the [doc](https://github.com/kohsuke/winsw/blob/master/doc/xmlConfigFile.md) says that environment variable expansion is allowed, it seems session or user level environment variables are not acknowledged. 

In the XML config file, we have 
`<description>%TestVariableName%</description>`

and from a powershell session, we try to set the variable as a local session environment variable. 
`$env:TestVariableName = "my_value"`
After starting the application via **winsw** we could observe that the variable value is not acknowledged. 

If set as a user level variable, it works if the logon type of the windows service is set to that user.
`[Environment]::SetEnvironmentVariable("TestVariableName", "my_value", "User")`

If set as a machine level variable, it works either as a system account or proper user. 
`[Environment]::SetEnvironmentVariable("TestVariableName", "my_value", "Machine")`

Our expected behaviour is that the local PowerShell session environment variables should also be honoured by **winsw**.

This might relate back to #238.

**Comment by NextTurn** [comment]
@oleg-nenashev Can you confirm this? I can't reproduce either this or #238.

**Versions**: WinSW.NET4.exe 2.2.0, 2.3.0

**Steps**:

*WinSW.xml*

```xml
<service>
    <id>%TEST_KEY%</id>
    <name>%TEST_KEY%</name>
    <description>%TEST_KEY%</description>
</service>
```

PowerShell scripts

```pwsh
$env:TEST_KEY = 'TEST_VALUE'
.\WinSW.exe install
```

Services

![image](https://user-images.githubusercontent.com/45985406/72665075-1b62d000-3a40-11ea-85ea-1b4bff7cffa5.png)

**Comment by oleg-nenashev** [comment]
Ok, will try to review ASAP
