### ISSUE TITLE
jvisualvm or jmc does not detct jvms running as windows service

### ISSUE THREAD

**Issue by ksanjeev9211** [winsw/winsw#306]

**Comment by oleg-nenashev** [comment]
You would need to run Java tools with the same account as the service. Usually it is a system administrator unless your service runs under another account

**Comment by jvmlet** [comment]
@ksanjeev9211 , please see this https://github.com/kohsuke/winsw/issues/150

**Comment by NextTurn** [comment]
Closing as a duplicate of #150.
