### ISSUE TITLE
 can not find network Hard Disk

### ISSUE THREAD

**Issue by wwwzzz5199** [winsw/winsw#307]
I have Mounted one network Hard Disk for windows server2012,and when I use winsw to regist service for my spring boot app,it can not find my network Hard Disk.but if I start my app by "java -jar xxx.jar" at  command line, the network Hard Disk can be found.

**Comment by oleg-nenashev** [comment]
Windows does not automatically map drives for services. Try https://github.com/kohsuke/winsw/blob/master/doc/extensions/sharedDirectoryMapper.md

**Comment by ztmmf** [comment]
> Windows does not automatically map drives for services. Try https://github.com/kohsuke/winsw/blob/master/doc/extensions/sharedDirectoryMapper.md

I used that solution but I got this：
winsw.Plugins.SharedDirectoryMapper.MapperException: Command net.exe  use Z: \\172.17.13.222 failed with code 2

**Comment by ztmmf** [comment]
when I changing my uncpath to "\\172.17.13.222\test" ，my service is always at the "starting"  and never sucess, and I can't stop it .

**Comment by NextTurn** [comment]
Another functionality that has been broken since its first introduction due to the misuse of `Process`. Sigh.

**Comment by oleg-nenashev** [comment]
FTR it was working well in my use-cases.  I am not a windows developer, and it was a time-constrained fix. So please bear with my code
