### ISSUE TITLE
Allow prompting for values

### ISSUE THREAD

**Issue by m8urnett** [winsw/winsw#308]
Allow for setting variables in the config file that are prompted for when using the `install` command. 

Example:

```
  <serviceaccount>
    <domain>YOURDOMAIN</domain>
    <user>{{PROMPT}}</user>
    <password>{{PROMPT}}</password>
    <allowservicelogon>true</allowservicelogon>
  </serviceaccount>
```

Alternative method:
```

<InstallPrompt>$user</InstallPrompt>
<InstallPrompt>$password</InstallPrompt>
...
    <user>$user</user>
    <password>$password</password>
```

Then when you install:

```
c:\> myservice.exe -install
Enter user:  username
Enter password:  *********

```

This would not only be a security improvement but would also allow for more portability. For example, including a winsw config with an app and prompting for the necessary values.

**Comment by oleg-nenashev** [comment]
Yes, it would be an interesting feature

**Comment by NextTurn** [comment]
What about auto prompting for missing values?

- Missing username
- Empty username
- Missing password
