### ISSUE TITLE
Is it possible to use winsw.exe to run the wrapped application?

### ISSUE THREAD

**Issue by nikolaybespalov** [winsw/winsw#312]
Hi guys, thanks for the cool project! Works like a charm!
But I'd like to ask you a couple questions.

I have the following myapp.xml:
```
<service>
  <id>myapp</id>
  <name>My App</name>
  <executable>java</executable>
  <arguments>-jar myapp.jar</arguments>
</service>
```
And myapp.exe which is a copy of winsw.exe.

What if I run myapp.exe without parameters? Will there be a run "java -jar myapp.jar"?

**Comment by NextTurn** [comment]
> Is it possible to use winsw.exe to run the wrapped application?

Yes. Try the `testwait` command, which "starts the service and waits until a key is pressed then stops the service".

> What if I run myapp.exe without parameters?

It will crash.
