### ISSUE TITLE
I can't read files from shared folder

### ISSUE THREAD

**Issue by gasperlf** [winsw/winsw#319]
I'm using winsw to create a java service, but I try to read files from a shared folder, but I can't access, when I run my java app without be a windows service is working but when I run like windows services no. how I can get a solution?

**Comment by oleg-nenashev** [comment]
https://github.com/kohsuke/winsw/blob/master/doc/extensions/sharedDirectoryMapper.md

**Comment by NextTurn** [comment]
Closing as answered. Feel free to file a new issue if more information is needed. Thanks.
