### ISSUE TITLE
How I can create a service type Network Service in Windows

### ISSUE THREAD

**Issue by gasperlf** [winsw/winsw#323]
Normally when you create a Windows service type Local System and that service do not have access to the network, I'd create a service with access network without login type Network Service, how I can do that?

**Comment by NextTurn** [comment]
The `LocalSystem` account and the `NetworkService` account have the right to access the network as the machine.

The `LocalService` account has the right to access the network as an anonymous user.

You may want to check your Firewall settings, etc.
