### ISSUE TITLE
ERROR - Failed to log event in Windows Event Log:

### ISSUE THREAD

**Issue by adidaslevy** [winsw/winsw#324]
I'm trying to run a node.js as a windows service. 
After configuring the xml file, and renaming, I got this issue: 

```
ERROR - Failed to log event in Windows Event Log: Starting [%ProgramFiles]\nodejs\node.exe D:\nodejswrapper\dist\server.js; Reason: 
System.ArgumentException: Source property was not set before writing to the event log.
   at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
   at System.Diagnostics.EventLog.WriteEntry(String message)
   at winsw.WrapperService.LogEvent(String message)
```

I installed winsw executable with windows sc utility.

**Comment by adidaslevy** [comment]
After installation using winsw install argument, I see no errors in log file created in directory, but service stops immediately: 

> 2019-06-03 18:39:06,625 INFO  - Starting ServiceWrapper in the service mode
> 2019-06-03 18:39:06,735 INFO  - Starting [%ProgramFiles]\nodejs\node.exe D:\nodejswrapper\dist\server.js
> 2019-06-03 18:39:06,744 INFO  - Starting [%ProgramFiles]\nodejs\node.exe D:\nodejswrapper\dist\server.js
> 2019-06-03 18:39:06,782 DEBUG - Completed. Exit code is 0

though when I run node dist\server.js from cmd, the server starts and stays.

**Comment by NextTurn** [comment]
Hi,

If you see this, please provide the XML configuration.
