### ISSUE TITLE
argument or arguments?

### ISSUE THREAD

**Issue by offa** [winsw/winsw#326]
According to the [documentation](https://github.com/kohsuke/winsw/blob/master/doc/xmlConfigFile.md#argument) `<argument>` should be used and `<arguments>` is available for backwards compatibility only.

However, except the mentioned documentation, `<arguments>` is used everywhere in this project instead.

Is there a reason not to use `<argument>…</argument>` or does the documentation need an update?

**Comment by NextTurn** [comment]
We support both! #532
