### ISSUE TITLE
Crash if roll-by-size-time defines sizeThreshold

### ISSUE THREAD

**Issue by dorkest-dork** [winsw/winsw#333]
Happens with v2.3.0.0 and the following configuration:

```
  <log mode="roll-by-size-time">
    <sizeThreshold>10240‬</sizeThreshold>
    <pattern>yyyyMMdd</pattern>
    <autoRollAtTime>00:00:00</autoRollAtTime>
    <zipOlderThanNumDays>7</zipOlderThanNumDays>
    <zipDateFormat>yyyyMM</zipDateFormat>
  </log>
```

And event log contains message below:

Service cannot be started. System.FormatException: Input string was not in a  correct format. at System.Number.StringToNumber(String str, NumberStyles  options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)  at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)  at winsw.ServiceDescriptor.get_LogHandler() at  winsw.WrapperService.CreateExecutableLogHandler() at  winsw.WrapperService.OnStart(String[] _) at  System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

Without sizeThreshold works fine.

**Comment by NextTurn** [comment]
There is a invisible U+202C character between `0` and `<` in your XML.

We do need to print some more user-friendly error messages.
