### ISSUE TITLE
Cant find dll when executable jar

### ISSUE THREAD

**Issue by yuanzzi** [winsw/winsw#336]
Hello!
Thanks for this useful software.

I was compile a java application and package a jar file. It was reference a dll with System.loadLibrary("") and I am sure  it could running normally with `cmd java -jar XX.jar`,So the dll must be in the correct path.

But when I set the service to winsw, It alway threw `java.lang.UnsatisfiedLinkError`, It looks like couldnt find dll.
What is the reason

Regards

**Comment by NextTurn** [comment]
Did you use a relative path for the DLL?

If so, please try specifying the `<workingdirectory>` setting.

**Comment by NextTurn** [comment]
Tracked by #444

**Comment by NextTurn** [comment]
@yuanzzi @BeeDance Is the DLL located in directories listed in the PATH environment variable or other special locations?

**Comment by NextTurn** [comment]
@yuanzzi Is the DLL located in directories listed in the PATH environment variable or other special locations?
