### ISSUE TITLE
When I wrappered  python.exe ,it give me this error

### ISSUE THREAD

**Issue by Mcdull0921** [winsw/winsw#339]
When I wrappered  Python.exe then give me this error:

Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

**Comment by oleg-nenashev** [comment]
Probably it is an environment issue, make sure that all env vars needed for Python are set up properly

**Comment by NextTurn** [comment]
This is probably a working directory issue. Please try specifying the `<workingdirectory>` setting.

Tracked by #444
