### ISSUE TITLE
Run service from python pip application

### ISSUE THREAD

**Issue by DevilCoreBlack** [winsw/winsw#343]
Hello.
I use Radicale Calendar/Contact server on Windows server thought python pip
When i start service, its starts normal, but it ends quickly.
If i use command «testwait» - pip application start correctly and work fine until i am not press some button and then stops command work correctly but it is not «start».

`<executable>python</executable>`
`<arguments>-m radicale --config "configs/config.ini"</arguments>`
`<stopparentprocessfirst>true</stopparentprocessfirst>`

How i can correctly start python pip applications?

**Comment by NextTurn** [comment]
> `"configs/config.ini"`

You need to specify the `<workingdirectory>` to make relative paths work properly.

Tracked by #444

**Comment by NextTurn** [comment]
There are some limitations of the `test` or `testwait` command. It's impossible to tell what could be wrong without taking a look at the logs.

**Comment by ylz-at** [comment]
I guess there is some problem with python apps. I tried to start a flask app on `localhost:8080` as a windows service. `winsw install`  and `winsw start` worked without any error, but I can't access the service on my localhost.

**Comment by Grendizr** [comment]
Hi @ylz-at .. any success on making the flask app work properly with `winsw` ? 
Thanks

**Comment by ylz-at** [comment]
@Grendizr not yet...
