### ISSUE TITLE
Test mode is not working with stoparguments

### ISSUE THREAD

**Issue by Project0** [winsw/winsw#347]
This seems to happen only when calling the "test" command
Instead of using the stopargument exclusively with the stopexecutable it tries to call stopexecutable +  stopargument + stopargument, arguments are suddenly quoted.

config:
```xml
  <executable>java.exe</executable>
  <arguments> -jar agent.jar</arguments>
  <stopargument>-NonInteractive -NoProfile -File C:\temp\stop.ps1</stopargument>
  <stopexecutable>powershell.exe</stopexecutable>
```

on test it tries to run:
`powershell.exe "-NonInteractive -NoProfile -File C:\temp\stop.ps1  -jar agent.jar"`

on normal service stop it seems to work fine:
`powershell.exe -NonInteractive -NoProfile -File C:\temp\stop.ps1`

**Comment by NextTurn** [comment]
https://github.com/winsw/winsw/blob/master/doc/xmlConfigFile.md#stopargumentstopexecutable

It's documented that you should use `<startargument>` if `<stopargument>` is specified.

`<argument>` will be appended to both specialized ones. This is undocumented but has 12 years of history...

There is no difference in arguments between `test` command and `start`/`stop` command
