### ISSUE TITLE
Picking env variables

### ISSUE THREAD

**Issue by sylvaingod** [winsw/winsw#349]
Hi, 

I am using winsw to start a spring boot java application in this way  :

<?xml version="1.0" encoding="UTF-8"?>
<service>
    <id>MyApp</id>
    <name>MyApp</name>
    <description>MyApp Windows Service</description>
    <executable>%BASE%\..\jre1.8.0_161\bin\java</executable>
    <arguments>-jar "MyApp.jar" --spring.config.location=%BASE%\..\conf\application.properties</arguments>
    <logmode>rotate</logmode>
</service>

For some reasons, when running Java, winsw is picking up the JAVA_TOOL_OPTIONS env variable. 

Why is that happening ? 
If I add <env name="JAVA_TOOL_OPTIONS" value="" />, and it worked. But is there a more elegant way of preventing winsw from picking up the env variables ? 

Thanks in advance for your help

Sylvain

Regards, 

Sylvain

**Comment by NextTurn** [comment]
AFAIK passing environment variables to child processes is a normal behavior for all operating systems.
