### ISSUE TITLE
Java - Unable to use system properties

### ISSUE THREAD

**Issue by bhushan-ind** [winsw/winsw#351]
I have a java program to get the windows logon username.
I have tried this:
System.getProperty("user.name"); 

I have also tried using JNA:
        char[] name = new char[200];
        Secur32.INSTANCE.GetUserNameEx(
                Secur32.EXTENDED_NAME_FORMAT.NameDisplay,
                name,
                new IntByReference(name.length)
        );
        String fullName = new String(name).trim();

Both of these approaches work fine when running as a independent java program, but when I run it as a service, the values are not correct.
Is it because the java program environment is not set correctly?

Thanks

**Comment by NextTurn** [comment]
The service is installed as the `LocalSystem` account by default. You have to provide the username and the password to install it as a user account.

Tracked by #444
