### ISSUE TITLE
Make <logpath> work with relative directories

### ISSUE THREAD

**Issue by abiaggi** [winsw/winsw#38]
At the moment <logpath> works only with full paths, doesn't work with relative paths.
It would be nice to have it work from the working directory of the .exe

Working:

``` xml
<logpath>C:\Program Files\My Service\logs</logpath>
```

Not working:

``` xml
<logpath>logs</logpath>
```

``` xml
<logpath>%CD%\logs</logpath>
```

Thanks,
Andrea

**Comment by Crotery** [comment]
+1
It is difficult to configure same service on several machines

**Comment by fabriciocolombo** [comment]
It woks using `env` configuration.

    <env name="JENKINS_HOME" value="%BASE%"/>
    <logpath>%JENKINS_HOME%\logs</logpath>

+1 for create the directory automatically

**Comment by 2933280** [comment]
why so complex?
\<logpath\>%BASE%\log\</logpath\> 

works fine ....

**Comment by Crotery** [comment]
Is %BASE% an env variable or special winsw string? We do not use Jenkins and do not want to add separate env variables for every deploy.

**Comment by oleg-nenashev** [comment]
`%BASE%` is a special WinSW string, Hence it can be used outside Jenkins as well (as any other WinSW component)

**Comment by oleg-nenashev** [comment]
At least now there are examples and user-visible documentation added in #170
