### ISSUE TITLE
the .exe modifies itself at runtime, making itself incompatible after initial run

### ISSUE THREAD

**Issue by mshade** [winsw/winsw#399]
I am able to install, test, and start the service using the 2.5.0 release of WinSW.NET461.exe artifact. However, at runtime, it moves itself to a `.bak` extension and replaces itself with an executable that will no longer start properly. After a stop and then start, I get an incompatibility warning, attached.

![Screen Shot 2020-02-04 at 4 11 40 PM](https://user-images.githubusercontent.com/393545/73787311-0b99fa00-4769-11ea-8cf2-04f5e1abb5eb.png)

I assume it's downloaded a more "recent" version of itself, but with the wrong dotnet framework version?

**Comment by mshade** [comment]
I was able to remedy this by declaring:

```
<configuration>
    <startup>
      <supportedRuntime version="v4.0" />
    </startup>
  </configuration>
```
in a `.exe.config` file -- however, the docs say this shouldn't be necessary with the dotnet-4 specific builds. I am also not really happy to see the binary changed out from under itself at runtime, that is some hostile behavior at first glance!

**Comment by oleg-nenashev** [comment]
Do you have the `download` feature enabled (self-update)?

**Comment by spicysomtam** [comment]
I am suffering this issue on 2.4.2. I was following this [this](https://hayato-iriumi.net/2019/05/23/how-to-install-jenkins-slave-as-windows-service/) guide. Just started looking at it. I'll let you know if I find a way round it.

**Comment by spicysomtam** [comment]
Found the issue. The link above names the .config file .conf, and thus its not read and replace by a binary for .net < 4.0! Then the binary wants to install .net 3.5 when 4.5 is already installed!

Also a oddity. I am using version 2.4.0. When I start the service, it renames the binary to .bak and replaces it with a 2.3.0 binary. Seems odd it down graded it? When I say version, I used the `version` arg to check the version.

**Comment by NextTurn** [comment]
To be clarified, .NET 4+ versions of WinSW will not request to install .NET 3.5. And WinSW didn't have self-updating functions. Even if something is configured to update it, the latest release version is 2.4.0 on [Jenkins releases](https://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/) and 2.6.2 on [Github releases](https://github.com/kohsuke/winsw/releases). Why did it download the 2.3.0 version?

**Comment by spicysomtam** [comment]
You missed the point about the `.exe.config` being called `.exe.conf` and being ignored:
```
<configuration>
  <startup>
    <supportedRuntime version="v4.0"/>
  </startup>
</configuration>
```
So that is why the .net < 4.0 binary was downloaded. 
I am using the jenkins releases (2.4.0 latest). Not familiar with the auto download process of the binary; let me read the docs to see if its mentioned.

**Comment by NextTurn** [comment]
> You missed the point about the `.exe.config` being called `.exe.conf` and being ignored:

The .NET 4 binary doesn't need the `.exe.config` file to specify the runtime version.

https://github.com/kohsuke/winsw/blob/master/doc/installation.md#making-winsw-1x-compatible-with-net-runtime-40

**Comment by spicysomtam** [comment]
This is windows server 2012 r2 with .net 4.5 installed. Its a long story why windows is an old release; lets say its a big platform (lots of servers), a big company, the business revolves around this platform and its not my call to upgrade it (although I have mentioned it in the past). I am not sure why it has .net 4.5 rather than the default (3.5?)t, other than we need to keep it up to date with security patching, as well as making it compatible with modern software, etc.

I think https://github.com/kohsuke/winsw/blob/master/doc/exeConfigFile.md could do with some docs? I had a quick look through and apart from the `download` section for the main config file, am not sure why it auto updates. I looked through the logging and could not see anything relating to the auto upgrade.To be honest the downgrade to 2.3.0 is not an issue as it works fine, but I wonder if it might be a problem in the future? Would be nice to turn off the auto upgrade feature?

**Comment by NextTurn** [comment]
Thanks for taking the time to report this issue! I've found the problem.

WinSW self-updating was implemented as a "feature" as a part of [JENKINS-19055](https://issues.jenkins-ci.org/browse/JENKINS-19055).

The 2.3.0 version is defined here: https://github.com/jenkinsci/jenkins/blob/3ebb9e3592d648bb0408634b8f92ec3b6fb0c54e/core/pom.xml#L796

@oleg-nenashev Maybe you still need to publish new releases to Jenkins Maven.

**Comment by spicysomtam** [comment]
I don't see it in the links you provide. I see the references to updating `slave.jar` using `download from`, but not the actual auto update of WinSW itself. 

Also how do you turn the auto update off?

**Comment by NextTurn** [comment]
The auto update is implemented in [Windows Agent Installer module](https://github.com/jenkinsci/windows-slave-installer-module).

See [Disabling Automatic upgrade](https://github.com/jenkinsci/windows-slave-installer-module/blob/660965ded6f726b934d5e8853803adbf001913b8/README.md#disabling-automatic-upgrade) for how to disable it.

**Comment by spicysomtam** [comment]
I vaguely get it: Somehow WinSW checks that pom file and thinks the latest version is 2.3.0 so it _upgrades_ it to that. A work around could be to just install v2.3.0?

**Comment by spicysomtam** [comment]
Holy moly, did not know about those docs. It would have been easier to follow the auto install than doing it manually. 

Thanks for all the help.

**Comment by spicysomtam** [comment]
I tried downgrading to 2.3.0, but the jenkins master still downloads its own version of winsw (2.3.0) and replaces your version (yours will be renamed to .bck).

For the benefit of others: If you are running Oracle jdk/jre on your client, and it has java web start (javaws), open a browser to your jenkins master, go to the windows agent node on the gui. Click the Launch button and open or download the .jnlp file.Then open the file with java web start and run it. When the agent is up and running, click on File and the Install as a service. Then open services (run services.msc) and check its running.

**Comment by NextTurn** [comment]
> I tried downgrading to 2.3.0, but the jenkins master still downloads its own version of winsw (2.3.0) and replaces your version (yours will be renamed to .bck).

IIUC it downloaded the .NET 2 version and replaces the .NET 4 one. The installer module currently determine versions by MD5 checksum of the binary rather than version strings.

The installer should be fixed to:

- Check version by parsing `winsw verison`.
- Do not downgrade.

**Comment by nxtn** [comment]
Closing as answered in https://github.com/winsw/winsw/issues/399#issuecomment-596057339.
