### ISSUE TITLE
Could not load file or assembly 'Microsoft.Management.Infrastructure' in .NET Core bundles

### ISSUE THREAD

**Issue by silenceleaf** [winsw/winsw#411]
all same config with 2.5.0 but I got 

.\WinSW.exe : System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
    + CategoryInfo          : NotSpecified: (System.IO.FileN...file specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

File name: 'Microsoft.Management.Infrastr
ucture, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at WMI.WmiRoot..ctor(String machineName)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

.\WinSW.exe : System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
    + CategoryInfo          : NotSpecified: (System.IO.FileN...file specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

File name: 'Microsoft.Management.Infrastr
ucture, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at WMI.WmiRoot..ctor(String machineName)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

**Comment by NextTurn** [comment]
Which asset are you using, .the *exe* or the *.zip*?

**Comment by NextTurn** [comment]
What's your OS version please?

**Comment by NextTurn** [comment]
My guess is that you were using .NET Core bundles on old versions of Windows. Note that .NET Core doesn't support Windows versions prior to Windows 7. 

See [.NET Core Supported OS Lifecycle Policy](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md) for details.

**Comment by silenceleaf** [comment]
> My guess is that you were using .NET Core bundles on old versions of Windows. Note that .NET Core doesn't support Windows versions prior to Windows 7.
> 
> See [.NET Core Supported OS Lifecycle Policy](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md) for details.

I am using windows server 2019.

**Comment by oleg-nenashev** [comment]
@silenceleaf Which particular configuration do you use? Is it a Nano server? And yes, which binary do you use?

**Comment by silenceleaf** [comment]
My config
`
<?xml version="1.0" encoding="UTF-8" ?>
<service>  
    <id>Aria2</id>  
    <name>Aria2</name>  
    <description>Aria2 download service</description>  
    <executable>D:\Apps\Utils\Aria2\aria2c.exe</executable>  
	<logpath>D:\Apps\Utils\Aria2\log\</logpath>
    <log mode="roll-by-size-time">
        <sizeThreshold>10240</sizeThreshold>
        <pattern>yyyyMMdd</pattern>
        <autoRollAtTime>00:00:00</autoRollAtTime>
        <zipOlderThanNumDays>5</zipOlderThanNumDays>
        <zipDateFormat>yyyyMM</zipDateFormat>
    </log>
    <depend></depend>  
    <startargument>--conf-path=D:\Apps\Utils\Aria2\aria2.conf</startargument>
</service>
`
Binary: WinSW.NETCore31.x64.exe
Version: 2.6

**Comment by silenceleaf** [comment]
Oh, by the way. I am using windows server 2019 core edition. which does have UI components.

**Comment by NextTurn** [comment]
Thanks for your report. It's a serious bug that the missing assembly isn't included in *WinSW.NETCore31.\*.exe* of Version 2.6.0.

I've opened dotnet/sdk#10665 on the SDK side. Even if it's really a bug in the SDK it won't be fixed very soon. For now we'll probably have to revert the changes in 2.6.0 as the simplest fix.

**Comment by oleg-nenashev** [comment]
https://github.com/kohsuke/winsw/releases/tag/winsw-v2.6.1 is out. Thanks to @NextTurn for the quick fix!

**Comment by oleg-nenashev** [comment]
Another follow-up for us is to have some kind of testing for .NET Core bundles. In addition to Unit tests, we could have blackbox smoke tests. Bonus points for running them in a fresh Windows container where we can really manage services...

**Comment by MrGrymReaper** [comment]
@oleg-nenashev When compiling are you actually doing this based on the preview releases of 3.1? If so could a temporary non-release test be run on a the release build of version 3.1 of .Net Core?

Just to make sure that it wasn't fixed after the preview release of .Net Core which the compilation of the actual build is done using?
