### ISSUE TITLE
Deprecating .NET 2.0 support?

### ISSUE THREAD

**Issue by oleg-nenashev** [winsw/winsw#434]
In 2020 .NET Framework 2.0 seems like a burden to maintain (setting up test environments, libaries and development tool which drop compatibility, etc.). .NET Core native packages can be used as a replacement for x86 and amd64 platforms, so maybe it is time to consider deprecating platforms and then dropping their support in a few months.

I know that .NET 2.0 packages are still used in many projects. E.g. we use them in Jenkins, but I am open to drop support of .NET 2.0 there. It would be great to get feedback from other users.

**Comment by NextTurn** [comment]
Yesterday I was just thinking about updating the installer module to select the appropriate artifact based on .NET versions installed...

.NET 2.0 is an obstacle especially when adding dependencies. Few packages still support the outdated platforms in latest versions.

And testing is a big concern. Although I managed to make codes compile with "macros", those old codes are not covered in CI testing. It's really dangerous to deliver untested products.

**Comment by dreamflow** [comment]
> It would be great to get feedback from other users.

i'm only doing .NET-Core . deprecating WinSW support for .NET-2.0 is ok for me .
i would even go further and suggest to consider to deprecate the support for running
WinSW on preinstalled .NET-runtimes altogether and instead going forward with
only natively compiled WinSW together with an embedded and trimmed
.NET-Core-Runtime .

**Comment by oleg-nenashev** [comment]
> would even go further and suggest to consider to deprecate the support for running WinSW on preinstalled .NET-runtimes

The problem with such approach is the size of a package. Right now x86 and amd64 packages for .NET Core 3.1 require around 65Mb. It is not that big for a standalone application, but it might become a problem for distributions which bundle WinSW. 

For example the entire jenkins.war is around 60Mb now, so bundling native executables would double the distribution size (or triple it if you take https://github.com/jenkinsci/windows-slave-installer-module). We could bring the number of bundled executables down to one, but it would be still a 50% size increase. It is totally possible to move all the bundling to a on-demand plugin, but this is a separate story which is probably not an option for other WinSW users.

**Comment by NextTurn** [comment]
> The problem with such approach is the size of a package. Right now x86 and amd64 packages for .NET Core 3.1 require around 65Mb. It is not that big for a standalone application, but it might become a problem for distributions which bundle WinSW.

I'll carry out an experiment to reduce the app size with some magic to explore the possibility of bundling .NET Core packages.

Anyway the .NET FX 4+ executable is an effective fallback since most machines will still have .NET Framework installed for a long time.

**Comment by NextTurn** [comment]
I've actually finished that experiment. The estimated result is that we can bring down the app size to ~20MB with little efforts, or ~12MB with great efforts.

**Comment by oleg-nenashev** [comment]
> I've actually finished that experiment. The estimated result is that we can bring down the app size to ~20MB with little efforts, or ~12MB with great efforts.

It is definitely great as an enhancement, and it would be great to complete the "little effort" part. At the same time I believe that non-native executables will still have a use-case, but we can limit thei support to recent versions of .NET

**Comment by NextTurn** [comment]
FYI [JENKINS-61862](https://issues.jenkins-ci.org/browse/JENKINS-61862)

**Comment by NextTurn** [comment]
Moving to v2 milestone as per the discussions in Gitter.

**Comment by NextTurn** [comment]
@oleg-nenashev Is this still in the scope of 2.x?

**Comment by oleg-nenashev** [comment]
Yes

**Comment by oleg-nenashev** [comment]
The codebase already drops the support. I am waiting for @buddhikac96 to finish the patches, and then we will release the new version with .NET 2.0 support removal

**Comment by NextTurn** [comment]
The code base still supports .NET 2.0.
