### ISSUE TITLE
Add a way to check compatibility with the target platform

### ISSUE THREAD

**Issue by oleg-nenashev** [winsw/winsw#437]
It is a follow-up to https://github.com/jenkinsci/jenkins/pull/4554 by @NextTurn . It would be great if WinSW users were able to check that WinSW is compatible with their platform before actually doing the service installation. Things to consider: OS version, .NET version, Win32 API availability, etc.

Implementation options: 

- Separate executable, maybe written in a native code
- ~NO GO~ we could invoke `winsw.exe check-platform` which would verify the system compatibility with the wrapper. The downside is that winsw would have to be runnable on lower .NET versions, and it is generally not possible unless you want to write unsafe main code or accept cryptic .NET startup messages

**Comment by NextTurn** [comment]
This would be an overkill. As said in #497, WinSW is just a .NET product with no special Windows API requirements.

Supported Windows versions will be documented in #608.

If .NET dependencies become an actual problem we'd have to consider rewriting it in a native language.
