### ISSUE TITLE
Platform-agnostic project name

### ISSUE THREAD

**Issue by NextTurn** [winsw/winsw#438]
It's possible that we port this product to Linux platforms. It might be better to not have "win" in the name at that moment.

I'm not very good at naming either. Maybe "JenkinsSW"?

**Comment by oleg-nenashev** [comment]
This tool is used not only for Jenkins, but also for many other use-cases. Although it might be possible if the project moves under the Jenkins umbrella, I would not consider this name as a first pick.

P.S: Don't ask me to suggest a name, we will likely end up with YASW (Yet Another Service Wrapper). At least it will totally justify the YAML support there 😄

**Comment by oleg-nenashev** [comment]
Time to add a "WinSW 3.x" milestone and group such items there?

**Comment by NextTurn** [comment]
> Time to add a "WinSW 3.x" milestone and group such items there?

Yes. And my plan is to ship non-breaking changes in v2.

**Comment by oleg-nenashev** [comment]
Why was it closed @NextTurn ?

**Comment by NextTurn** [comment]
In terms of the development speed, it's unlikely to port it to other platforms.

In addition, systemd is much more powerful than WinSW. The latter looks more like a ported version of the former to Windows.
