### ISSUE TITLE
Reconfigure CI to use the new GitHub repo location

### ISSUE THREAD

**Issue by oleg-nenashev** [winsw/winsw#447]
CI does not longer work after the project's migration to the new location. A fix is needed

**Comment by oleg-nenashev** [comment]
CI has been reconfigured and moved to an organization: https://ci.appveyor.com/project/winsw/winsw
@NextTurn if you provide your Appveyor account, I will add you to the org

**Comment by NextTurn** [comment]
What about we switch to Azure Pipelines?

**Comment by oleg-nenashev** [comment]
Yes, it is also fine. And it is likely to be preferable for a .NET project
