### ISSUE TITLE
Document supported Windows versions

### ISSUE THREAD

**Issue by oleg-nenashev** [winsw/winsw#497]
Currently there is no explicit documentation which Windows versions are supported. We have some documentation for supported .NET versions which can be used to make assumptions, but these assumptions are not guaranteed to be correct due to the usage of WinAPI in some cases.

It would be great to explicitly list the supported versions.

**Comment by NextTurn** [comment]
Also note that .NET Core is using APIs available only on Windows 7 and later versions.

https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md

**Comment by NextTurn** [comment]
Our OS support is determined by the runtime. .NET Framework 4.6.1 and the current .NET Core version only supports Windows 7+.

I do not think the project itself is using any Windows API that isn't available on Windows XP.
