### ISSUE TITLE
Revise xmlConfigFile.md for v2.x and future v3.x WinSW series

### ISSUE THREAD

**Issue by MrGrymReaper** [winsw/winsw#517]
Currently the documentation written for the xml configuration file is very much out of date and doesn't contain up to date information. Even as new features are added to the windows service wrapper, the information about configuring them and the options available haven't been added.

Thus people are likely to be unable to properly configure the wrapper for their software to the appropriate settings.

Also information specific to the version 1.00 of the wrapper are likely still present in the documentation, if it still needs to be preserved. Then possibly spin off the config file information into two forms, one for the older version and the other for the newer versions.

Alternatively the documentation could contain notes about compatibility with specific versions of the service wrapper software.

**Comment by oleg-nenashev** [comment]
Hi, thanks for the feedback! Some docs might be missing, but the docs are intended to be aligned with the current version.

Could you please list items which are missing and, if possible, create separate tickets for them? It would help to fix the documentation issues gradually

**Comment by MrGrymReaper** [comment]
Download action attribute settings from recent update aren't currently documented. #518

**Comment by MrGrymReaper** [comment]
Also the SecurityDescriptor settings are sill un-included in the xml config file documentation. Even though the feature has been included in the version 2.7.0 release. #519

**Comment by MrGrymReaper** [comment]
Waithint setting's options (attributes) etc aren't currently included in the documentation. #520

**Comment by MrGrymReaper** [comment]
Here's a list of things which I have noticed missing from the documentation so far. There's possibly others as well. So if anyone else notices things like this missing from my list, please feel free to do as @oleg-nenashev suggests.

Which is to add them to this list I have started and if possible open separate issues for them under documentation category.

**Comment by NextTurn** [comment]
> Also information specific to the version 1.00 of the wrapper are likely still present in the documentation

I think I've removed all information specific to v1.x recently (except *puppetWinSW.md*) and can't find more. Could you please list some outdated items? Thanks.

**Comment by oleg-nenashev** [comment]
Thanks for creating some documentation issues @MrGrymReaper ! I will try to follow-up on them next weekend
