### ISSUE TITLE
SecurityDescriptor is undocumented

### ISSUE THREAD

**Issue by MrGrymReaper** [winsw/winsw#519]
Currently the SecurityDescriptor options which were added in the version 2.7.0 update, still hasn't been included in the documentation (xmlConfigFile.md). This is required for properly configuring these settings in the wrapper software.

**Comment by NextTurn** [comment]
I remember that I added a small entry in https://github.com/winsw/winsw/pull/431/files#diff-e90c46eaa11fbf162ec92e792b51d27a. What could be wrong?

**Comment by NextTurn** [comment]
No reply from the author.
