### ISSUE TITLE
Waithint setting missing in xmlconfigfile.md

### ISSUE THREAD

**Issue by MrGrymReaper** [winsw/winsw#520]
Currently the waithint setting is missing from the xmlconfigfile.md documentation so people can't know what it can be set to. A bug fix is meantioned in one of the release notes for a released version, however it isn't included in documentation.

**Comment by NextTurn** [comment]
`<waithint>` is currently broken and to be fixed by #417.

**Comment by oleg-nenashev** [comment]
Setting was fixed in 2.9.0: https://github.com/winsw/winsw/releases/tag/v2.9.0 . Would be great if someone documents it

**Comment by NextTurn** [comment]
I decided not to include it in docs. There is nothing interesting to configure.

You don't need to set it yourself.
