### ISSUE TITLE
Explanation of different binaries

### ISSUE THREAD

**Issue by chiflux** [winsw/winsw#523]
It would be good, if there would be a detailed explanation, why there are different binaries and what the purpose and/or unique value of each binary is?

- WinSW.NET2.exe
- WinSW.NET4.exe
- WinSW.NET461.exe
- WinSW.NETCore31.x64.exe
- WinSW.NETCore31.x86.exe
- WinSW.NETCore31.zip

**Comment by NextTurn** [comment]
See also #416, #421

**Comment by chiflux** [comment]
I like self contained versions, but I don't understand why there are so many.

**Comment by NextTurn** [comment]
My short answer:

*NET2.exe*/*NET4.exe*/*NET461.exe* are the original deliverables. Newer versions are added over time and older versions are kept for compatibility.

When self-contained binaries were first introduced, we made them single-file executables to adapt to the existing packaging scheme.

It's known that single-file executables are self-extracting files. For those who don't need such executables, I planned to publish self-contained archives (#421) to reduce startup time and footprint.

See also #416 for .NET Core packages.

/cc @oleg-nenashev if he has anything to add.

**Comment by NextTurn** [comment]
I'm closing this in the hope that it has been answered. README has also been updated to explain the executables.

> WinSW offers executables for .NET Framework 2.0, 4.0 and 4.6.1. It can run on Windows platforms which have these versions of .NET Framework installed. For systems without .NET Framework, the project provides native 64-bit and 32-bit executables which are based on .NET Core 3.1.

**Comment by NextTurn** [comment]
We are now shipping self-contained *.zip* files which are only half the size of corresponding *.exe* files.

- WinSW.NETCore.x64.exe
- WinSW.NETCore.x86.exe
- WinSW.NETCore.x64.zip
- WinSW.NETCore.x86.zip
