### ISSUE TITLE
Contributor guidelines: Document the project structure

### ISSUE THREAD

**Issue by oleg-nenashev** [winsw/winsw#529]
As agreed at the GSoC meeting, we would like to have a  code dive into the project. As a result, we will  document the project structure and main components.

Acceptance criteria:

- [x] - A code dive session is conducted together by @oleg-nenashev @NextTurn and @buddhikac96 
- [ ] - A new developer guide is created and linked from CONTRIBUTING.md
- [ ] - The guide includes overview of the project
- [ ] - The guide includes link to the recorded overview video

**Comment by oleg-nenashev** [comment]
I have started a Doodle to find an optimal meeting time: https://doodle.com/poll/my645qq28pmmyy2x . Everyone is welcome to join if you are interested in the project development. CC @mikecirioli

**Comment by oleg-nenashev** [comment]
Recording of the Knowledge transfer session: https://youtu.be/_adhRj19ESY

**Comment by NextTurn** [comment]
Done in #534.
