### ISSUE TITLE
WinSW v2.9.0 not available on NuGet

### ISSUE THREAD

**Issue by offa** [winsw/winsw#533]
The latest release v2.9.0 is not available through NuGet yet.

## Steps to reproduce

1. Visit https://www.nuget.org/packages/WinSW/
1. Latest package available is 2.8.0

## Environment

NuGet / Windows

## Possible Solution

Upload package.

**Comment by oleg-nenashev** [comment]
Yes, the release Pipeline went wrong. Fixing it

**Comment by oleg-nenashev** [comment]
Fixed the Pipeline. Package is being verified by NuGet now, will take some time.

![image](https://user-images.githubusercontent.com/3000480/81681666-b4d14a00-9454-11ea-874b-bc622984cc0d.png)

**Comment by oleg-nenashev** [comment]
It is published now. @offa please let me know if there are any issues with the package. I tested it locally for a few configurations, looks OK.

**Comment by offa** [comment]
Thanks, no problems with 2.9.0.

**Comment by oleg-nenashev** [comment]
You are welcome! And thanks for reporting it
