### ISSUE TITLE
YAML Schema Validation  (GSoC - 2020)

### ISSUE THREAD

**Issue by buddhikac96** [winsw/winsw#537]
Windows Service Wrapper will be updated for YAML configuration support as a part of GSoC 2020.  This issue is for schema validation for the YAML configuration file. Current plan is to validate YAML configuration file with a JSON schema.  I @buddhikac96 will work on this issue as part of GSoC 2020 coding phase 02. 

Acceptance Criteria 

- [x] - JSON Schema file (As a embedded resource)
- [x] - Documentation for the JSON Schema.
- [ ] - YAML file validation with JSON Schema 
- [ ] - Unit test for validation

**Comment by oleg-nenashev** [comment]
@buddhikac96 I think the acceptance criteria items should be rather separate items, because they can be delivered independently. Acceptance criteria should rather include items like "documentation" or "test automation" for separate deliverables
