### ISSUE TITLE
YAML Schema validation (GSoC - 2020)

### ISSUE THREAD

**Issue by buddhikac96** [winsw/winsw#540]
Windows Service Wrapper will be updated for YAML configuration support as a part of GSoC 2020.  This issue is for schema validation for the YAML configuration file. Current plan is to validate YAML configuration file with a JSON schema.  I @buddhikac96 will work on this issue as part of GSoC 2020 coding phase 02. 

Acceptance Criteria 

- [ ] - Schema validation against JSON schema file (https://github.com/winsw/winsw/issues/537)
- [ ] - Unit test for validation

**Comment by NextTurn** [comment]
Why do we need so many new issues?

**Comment by buddhikac96** [comment]
We need to create issues related to GSoC Phase 1 before starting coding in phase 1. These are the issues that I'm going to fix on GSoC phase 1.  :)

**Comment by buddhikac96** [comment]
Duplicate issue of https://github.com/winsw/winsw/issues/537. Closing the Issue
