### ISSUE TITLE
startup windows service with winsw,couldn't detect JVM using jps

### ISSUE THREAD

**Issue by zjphdh2604** [winsw/winsw#541]
if i start a JVM directly   java -jar demo.jar ,i can use jps command and detect the pid,but when i use winsw, use jps couldn't list infomation
![T}JO~MDR%P_1%IWUUL6X 1](https://user-images.githubusercontent.com/4235046/82965673-5df27580-9ffb-11ea-9c1c-316444dcee86.png)

**Comment by NextTurn** [comment]
See #150

**Comment by zjphdh2604** [comment]
thanks a lot.

**Comment by wudg** [comment]
> See #150

JPS still can't query the java process started with winsw, and the solution link given in # 150 has expired. Is there any specific solution? Thanks
