### ISSUE TITLE
register wsl(Windows Subsystem for Linux) service failure

### ISSUE THREAD

**Issue by androllen** [winsw/winsw#545]
Hi~  
hava a try use winsw that register wsl `service ssh start`  
because open wsl then input `sudo service ssh start` so that waste time
if I could use winsw register wsl ssh service status that would save time  
Below is my solution

```sh
# save winse.xml
<service>
    <id>wslsw</id>
    <name>lable</name>
    <description>lable</description>
    <executable>bash</executable>
    <startarguments>-c 'sudo service ssh start'</startarguments>
    <stoparguments>-c 'sudo service ssh stop'</stoparguments>
    <env name="PATH" value="C:\Windows\System32" />
</service>
```

winsw.exe install  
winsw.exe start  

but this is a invalid method ，may be bash.exe is system level ??

thanks!

**Comment by msenturk** [comment]
Maybe try like this :

<executable>%windir%\System32\bash.exe</executable>
<startarguments>-c "sudo /etc/init.d/ssh start"</startarguments>

**Comment by androllen** [comment]
> Maybe try like this :
> 
> ```
> <executable>%windir%\System32\bash.exe</executable>
> <startarguments>-c "sudo /etc/init.d/ssh start"</startarguments>
> ```

thanks!

add no password permissions
```sh
  sudo chmod u+w /etc/sudoers
  sudo vim /etc/sudoers
  androllen ALL=(ALL) NOPASSWD: ALL
  sudo chmod u-w /etc/sudoers
```
but status still stopped  
![image](https://user-images.githubusercontent.com/5212108/83971682-38c10980-a90f-11ea-9d12-3c94c1639095.png)

-_-!

**Comment by NextTurn** [comment]
`bash` will exit after executing the commands. You can append a command to wait for the daemon to finish.

Hint:

```bash
for pid in $(pidof sshd); do tail --pid=$pid -f /dev/null; done
```

**Comment by captainnx** [comment]
https://github.com/winsw/winsw/issues/545#issuecomment-649942814

it not work
