### ISSUE TITLE
Starting the service starts two processes

### ISSUE THREAD

**Issue by pppigg** [winsw/winsw#546]
Nginx was successfully registered as the Window service according to the documentation.But when I open task manager, two nginx.exes exist in the background process.
I don't know if this is normal, or what's missing in the XML file.

nginx.xml
```
<service>

 <id>nginx</id>

 <name>nginx</name>

 <description>nginx</description>

 <logpath>D:\deploy\nginx-1.18.0\servicelogs</logpath>

 <log mode='roll-by-time'>
    <pattern>yyyyMMdd</pattern>
 </log>

 <depend></depend>

  <executable>D:\deploy\nginx-1.18.0\nginx.exe</executable>

  <stopexecutable>D:\deploy\nginx-1.18.0\nginx.exe -s stop</stopexecutable>

</service>
```

Does calling nginx_service.exe stop directly kill the process starting the service? This is that when I register the self-generated exe file as a service using WinSW, there is no configuration like StopEXECUTABLE in the XML file.

**Comment by NextTurn** [comment]
Nginx starts a child process itself.

I recommend [Process Explorer](https://docs.microsoft.com/sysinternals/downloads/process-explorer).

![image](https://user-images.githubusercontent.com/45985406/85818690-d8054e00-b7a3-11ea-88da-11f30917f91c.png)
