### ISSUE TITLE
Issue #319

### ISSUE THREAD

**Issue by ankurpramanik** [winsw/winsw#551]
```xml
 <extensions>
    <extension enabled="true" className="winsw.Plugins.SharedDirectoryMapper.SharedDirectoryMapper" id="mapNetworDirs">
      <mapping>
        <map enabled="false" label="C:\New\folder" uncpath="\\54.98.245.23"/>
      </mapping>
    </extension>
  </extensions>
```

If I put "<map enabled="false" ..." Sercice is starting but " The specified server cannot perform the requested operation. " this exception is comming.

But If I put "<map enabled="true" ..." service is not starting.

I am accessing Ubuntu share path,  from java code path is accessed fine but when I create service error is comming. need help, and also explain the functionality of mapping.

in this link https://github.com/winsw/winsw/blob/master/doc/extensions/sharedDirectoryMapper.md 
no description is present. please explain why I should write mapping

**Comment by NextTurn** [comment]
> `<map enabled="false" label="C:\New\folder" uncpath="\\54.98.245.23"/>`

`label` should be a label, e.g. `"C:"`.

> But If I put "<map enabled="true" ..." service is not starting.

The next time you encounter a problem please check the log.

**Comment by NextTurn** [comment]
It's unclear what's going on here. The "net use" command is very old and only supports establishing connections for a single user (at a time). When you were "accessing Ubuntu share path, from java code path" you were in your logged on user's context, while your service apparently didn't run in that context. (Did you configure the `<serviceaccount>`?)
