### ISSUE TITLE
RunawayProcessKiller

### ISSUE THREAD

**Issue by chiflux** [winsw/winsw#552]
**The usage of the RunawayProcessKiller is unclear.**

- Looking at the example, it seems to rely on a configurable pid.txt file. It is completely unclear where this file is coming from or what component is creating it. At least it seems not to be created automatically. 
- Also there is a discussion about an ENV variable check that would prevent the killing of a wrong proccess. 

It seems to me that there is not yet sufficient documentation for this extension. A consolidated example would also be helpful.

**Comment by NextTurn** [comment]
> * Looking at the example, it seems to rely on a configurable pid.txt file. It is completely unclear where this file is coming from or what component is creating it. At least it seems not to be created automatically.

You specify an arbitrary file path and WinSW uses it to store the process ID.

> * Also there is a discussion about an ENV variable check that would prevent the killing of a wrong process.

WinSW checks the `WINSW_SERVICE_ID` environment variable. This is an implementation detail unless your program overwrites the variable.

**Comment by chiflux** [comment]
Wow. This was quick. Thanks!
So the `WINSW_SERVICE_ID` variable is set by WinSW for the running process and checked before killing a (suspected) "runaway process" defined by the content of the pid.txt?

**Comment by NextTurn** [comment]
Yes. Note that the `WINSW_SERVICE_ID` variable is not documented so don't rely on it in your programs.

**Comment by oleg-nenashev** [comment]
FTR there is https://github.com/winsw/winsw/pull/440 from @NextTurn which replaces Runaway Process Killer by the OS features
