### ISSUE TITLE
how to run java.exe -jar xx.jar as Admin

### ISSUE THREAD

**Issue by BeeDance** [winsw/winsw#577]
### Problem statement
I need run java.exe -jar xx.jar as Admin privilege. when i run this command in cmd window(Administrator:Command Prompt) that works,but not worked when i use winsw run this command.

this picture is what i want. anyone can help me?
![image](https://user-images.githubusercontent.com/6102853/87392146-9adfef00-c5de-11ea-95b2-1515eaaf105f.png)

**Comment by NextTurn** [comment]
Is `xx.jar` a relative path?

**Comment by BeeDance** [comment]
yes

**Comment by NextTurn** [comment]
Please configure the `<workingdirectory>` if `xx.jar` is a relative path.

I really hate such unclear issues. We've had a ton of issues w.r.t. the use of relative paths. That said, I didn't say we won't change the default behaviors to reduce these problems.

**Comment by BeeDance** [comment]
sorry, my description is unclear.
what i mean is  winsw can run my command but the privilege is may not Admin.
but, when i use (Administrator:Command Prompt) run my command ,all function is ok.
so, i want know is that have a place to configure  privilege or there are other ways to achieve it. thanks

**Comment by NextTurn** [comment]
How did you conclude that it's not Admin? If you don't configure the `<serviceaccount>`, WinSW installs the service in the system account, which has even higher privileges than Admin.

**Comment by BeeDance** [comment]
oh,I figured out the problem.thanks.

**Comment by NextTurn** [comment]
Good to hear that.

**Comment by NextTurn** [comment]
@BeeDance Is `xx.jar` located in directories listed in the PATH environment variable or other special locations?

**Comment by WJME** [comment]
> ### Problem statement
> I need run java.exe -jar xx.jar as Admin privilege. when i run this command in cmd window(Administrator:Command Prompt) that works,but not worked when i use winsw run this command.
> 
> this picture is what i want. anyone can help me? ![image](https://user-images.githubusercontent.com/6102853/87392146-9adfef00-c5de-11ea-95b2-1515eaaf105f.png)

Please tell me how you got him running well.  I encountered the same problem. I used jdbc in the jar package to read the acess database in the Windows shared file directory, and received a prompt saying that there is a permission problem, but it is effective to run it directly on the cmd command line

error message: 
If you're using mapped drives to access database files, you may need to check the security permissions.
