### ISSUE TITLE
Set a default working directory

### ISSUE THREAD

**Issue by NextTurn** [winsw/winsw#578]
### Feature Request

**Problem statement.**
Set a default working directory to reduce relative path issues.

**Describe the solution you'd like.**
Use the directory where the binary is located.

**Describe alternatives you've considered.**
Use the directory where the config file is located.

**Comment by NextTurn** [comment]
I personally don't favor this, though.

**Comment by oleg-nenashev** [comment]
`Use the directory where the config file is located.` or `where executable is located` would be a way to go IMHO
