### ISSUE TITLE
Winsw tries to create an eventlog source which fails if the service isn't running with admin permissions

### ISSUE THREAD

**Issue by pvandervelde** [winsw/winsw#61]
Winsw upon first start tries to access an eventlog with the same name as the service ID. If that event log source does not exist and the service is not running with admin permissions then a security exception is thrown with a message like:

```
Failed to log event in Windows Event Log: envar JENKINS_HOME=c:\ci; Reason: 
Message:The source was not found, but some or all event logs could not be searched.  
To create the source, you need permission to read all event logs to make sure that the 
new source name is unique.  
Inaccessible logs: Security.
```

This is caused by the fact that normal users do not have permissions to all of the event logs.

The solution is to create the eventlog source prior to starting the service. 

It would be useful if this fact was documented given that it's very hard to determine that this problem exists without log files.

**Comment by oleg-nenashev** [comment]
It makes sense to add an additional analysis in any case

**Comment by oleg-nenashev** [comment]
Will fix it after 2.0

**Comment by altxt** [comment]
For some reason the event source was not created during Jenkins setup.
Fix: run as admin
```powershell
$source = 'jenkins'
if ([System.Diagnostics.EventLog]::SourceExists($source) -eq $false) {
  [System.Diagnostics.EventLog]::CreateEventSource($source, "Application")
}

```

**Comment by nxtn** [comment]
@altxt Version?

**Comment by altxt** [comment]
Jenkins 2.163.1
jenkins.exe version
`WinSW 2.9.0.0`
