### ISSUE TITLE
Is `executable` so confusing?

### ISSUE THREAD

**Issue by nxtn** [winsw/winsw#624]
### Rationale

In order to avoid undetectable errors caused by putting multiple arguments in single argument settings, `argument` has been removed in favor of `arguments`. However, I keep seeing configuration where arguments are placed in paths. Two recent samples are https://github.com/winsw/winsw/issues/300#issuecomment-613464399 and https://github.com/winsw/winsw/issues/546#issue-635960359. In such cases WinSW simply fails with `ERROR_FILE_NOT_FOUND`. (You must know how many such bug reports we have had, due to various causes.) Is `executable` a name so confusing to make it unclear that it's a path? Thus, I have the following proposals to avoid or recovering from these errors.

### Proposals

1. Rename `executable` to `executablePath`/`exePath`/`binaryPath`/`filePath`/`path` to clarify it's a path.

2. Merge `executable` and `arguments` into a single setting entry. A well-behaved 32-bit or 64-bit Windows app will join them before performing a system call anyway.

3. Do not touch the current configuration schema. If creating process failed with `ERROR_FILE_NOT_FOUND`, the first part of `executable` is a path and `arguments` isn't specified, retry with `executable` as the whole command line.

**Comment by majkinetor** [comment]
It was not for me. I correctly deduced it must be path or it would be named something like `command`. Two missuses do not qualify as a problem. Are there more of it ?

**Comment by nxtn** [comment]
There are more in #116.

Yeah, of course. `executable` is just fine until we rename `arguments` to `args`.

**Comment by nxtn** [comment]
@oleg-nenashev When do you plan to take a look at these stale issues?
