### ISSUE TITLE
service cannot stop

### ISSUE THREAD

**Issue by krikil86** [winsw/winsw#627]
I cannot stop service. When I stop the service, a warning appears **Windows could not stop the Sinkron Kace service on Local Computer. The service did not return an eerror. This could be an internal Windows errro or an internal service error. If the problem persists, contach your system administrator.**

## Steps to reproduce

I open services.msc and right click on service Sinkron Kace and choose Stop.
here my xml

```
<service>
    <id>sinkron_kace</id>
    <name>Sinkron Kace</name>
    <description>Program bantu Kace</description>
    <logpath>%ALLUSERSPROFILE%\sinkron kace\logs</logpath>
    <executable>%PROGRAMFILES%\sinkron kace\sinkron_kace.exe</executable>
    <log mode="reset"/>
    <onfailure action="restart" />
</service>
```

## Environment

* WinSW version : 3.0.0.0 (WinSW v3.0.0-alpha.2)
* WinSW package type : NET 4.6.1
* Windows version : Windows 7 Professional 32-bit (6.1, Build 7601)
* Net Framework Installed on Windows : 4.7.2

**Comment by NextTurn** [comment]
Thank you for trying the alpha releases. Any logs?

**Comment by krikil86** [comment]
> Thank you for trying the alpha releases. Any logs?

2020-08-05 09:47:13,454 DEBUG - Completed. Exit code is 0
2020-08-05 09:47:26,671 DEBUG - Starting WinSW in service mode
2020-08-05 09:47:26,716 INFO  - Starting C:\Program Files\sinkron kace\sinkron_kace.exe
2020-08-05 09:47:26,802 INFO  - Started process 9992
2020-08-05 09:47:26,803 DEBUG - Forwarding logs of the process System.Diagnostics.Process (sinkron_kace) to WinSW.ResetLogAppender

**Comment by NextTurn** [comment]
> System.ComponentModel.Win32Exception (0x80004005): Access is denied

This stupid bug has been fixed in the code base.

> Failed to attach to console. A device attached to the system is not functioning

This is an unexpected external error. If the Windows API isn't working we'll have to kill the process as a fallback.
