### ISSUE TITLE
Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0

### ISSUE THREAD

**Issue by krikil86** [winsw/winsw#633]
### Problem statement

When i run command **winsw status** i get error **Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0**.
I use Windows 10 Enterprise 2015 LTSB 32-bit (10.0,Build 10240) and cannot instal Net Framework 4.7.2 so i use Net Framework 4.6.2. How to solve this problem?

```
C:\Windows\system32>winsw.exe uninstall

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at System.CommandLine.Builder.CommandLineBuilder..ctor(Command rootCommand)
   at WinSW.Program.Run(String[] args)
   at WinSW.Program.Main(String[] args)
```

## Environment

* WinSW version : 3.0.0.0 (WinSW v3.0.0-alpha.2)
* WinSW package type : NET 4.6.1
* Windows version : Windows 10 Enterprise 2015 LTSB 32-bit (10.0,Build 10240)
* Net Framework Installed on Windows : 4.6.2

**Comment by NextTurn** [comment]
Fixed in #632.
