### ISSUE TITLE
Regression: Service does not install with new version 2.10.0

### ISSUE THREAD

**Issue by felfert** [winsw/winsw#659]
**Summary**.
We have an automated script running each weekend which provisions and snapshots various windows build-slaves for
our internal jenkins CI. Basically it works like this:

Step1 (powershell, run before snapshotting the VM)

````
...
choco install nuget
nuget install winsw
copy executable to C:\Users\jenkins\jenkins-slave.exe
create a template file C:\Users\jenkins\jenkins-slave.xml.template
...
````
Later, when jenkins provisions the build-slave from that image via jclouds, it runs another powershell script which creates the actual xml config at C:\Users\jenkins\jenkins-slave.xml (replacing various placeholders in the xml template), resulting in the following XML content. (Note: No problem sharing passwords/secrets, because those are generated anyway and valid only once for that specific instance). After that, it invokes 

`C:\Users\jenkins\jenkins-slave.exe install`
and
`C:\Users\jenkins\jenkins-slave.exe restart`

Until version 2.9.0, this worked nicely. With version 2.10.0 however, the invocation of `C:\Users\jenkins\jenkins-slave.exe install` returns with some random negative exit code and does **not** install the service despite printing the usual message `2020-08-24 22:06:09,909 INFO  - Installing the service with id 'jenkins'`

````
<configuration>
    <id>jenkins</id>
    <name>Jenkins slave agent</name>
    <description>This service runs an agent for Jenkins automation server.</description>
    <executable>java.exe</executable>
    <arguments>-Xrs -Xmx256m -jar "%BASE%\slave.jar" -noCertificateCheck -jnlpUrl "http://jenkins.openstack.intern/computer/bh-w2019-54b/slave-agent.jnlp" -secret "36305138e9236efb29a77cbd837d376f826ff65b945ab81e856f624c295bc669"</arguments>
    <logmode>rotate</logmode>
    <startmode>automatic</startmode>
    <onfailure action="restart" delay="10 sec"/>
    <download from="http://jenkins.openstack.intern/jnlpJars/agent.jar" to="%BASE%\slave.jar" />
    <extensions>
        <!-- This is a sample configuration for the RunawayProcessKiller extension. -->
        <extension enabled="true" 
               className="winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension"
               id="killOnStartup">
            <pidfile>%BASE%\jenkins_agent.pid</pidfile>
            <stopTimeout>5000</stopTimeout>
            <stopParentFirst>false</stopParentFirst>
        </extension>
    </extensions>
    <serviceaccount>
       <domain>BH-W2019-54B</domain>
       <user>jenkins</user>
       <password><![CDATA[MRT]S9=ibtp[Emcs]]></password>
       <allowservicelogon>true</allowservicelogon>
    </serviceaccount>
</configuration>
````
## Environment

* WinSW version: 2.10.0
* WinSW package type: nuget
* Windows version: any
* Wrapped executable and version: Does not matter

Workaround: For now, I just pin the version of WinSW to 2.9.0 on the nuget install commandline.

**Comment by oleg-nenashev** [comment]
> Until version 2.9.0, this worked nicely. With version 2.10.0 however, the invocation of C:\Users\jenkins\jenkins-slave.exe install returns with some random negative exit code and does not install the service despite printing the usual message

Hi @felfert , thanks for reporting! Would it be possible to get this error code? Also, there might be additional information in the event log

**Comment by felfert** [comment]
Yep, I have to setup a test VM with WinSW 2.10.0 manually, so it takes a little bit..

**Comment by felfert** [comment]
Just realized, that I had the exit code in some internal chat history:

```
PS C:\windows\system32> C:\Users\jenkins\jenkins-slave.exe install
2020-08-24 16:45:08,703 INFO - Installing the service with id 'jenkins'
PS C:\windows\system32> $lastexitcode
-1073740940
```

For the event log, that will take a little bit

**Comment by felfert** [comment]
There is exactly one related event in the windows event log indicating an application crash:
````
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Events><Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Application Error'/><EventID Qualifiers='0'>1000</EventID><Level>2</Level><Task>100</Task><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2020-08-24T21:31:05.468150000Z'/><EventRecordID>2027</EventRecordID><Channel>Application</Channel><Computer>bh-w2016-956</Computer><Security/></System><EventData><Data>jenkins-slave.exe</Data><Data>2.10.0.0</Data><Data>5f40e5fe</Data><Data>ntdll.dll</Data><Data>10.0.14393.3630</Data><Data>5e8d4386</Data><Data>c0000374</Data><Data>00000000000f7a13</Data><Data>c44</Data><Data>01d67a5ddd19630c</Data><Data>C:\Users\jenkins\jenkins-slave.exe</Data><Data>C:\windows\SYSTEM32\ntdll.dll</Data><Data>7c6e72d0-6492-4a1f-8b1b-9418d10db02f</Data><Data></Data><Data></Data></EventData><RenderingInfo Culture='en-US'><Message>Faulting application name: jenkins-slave.exe, version: 2.10.0.0, time stamp: 0x5f40e5fe
Faulting module name: ntdll.dll, version: 10.0.14393.3630, time stamp: 0x5e8d4386
Exception code: 0xc0000374
Fault offset: 0x00000000000f7a13
Faulting process id: 0xc44
Faulting application start time: 0x01d67a5ddd19630c
Faulting application path: C:\Users\jenkins\jenkins-slave.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: 7c6e72d0-6492-4a1f-8b1b-9418d10db02f
Faulting package full name: 
Faulting package-relative application ID: </Message><Level>Error</Level><Task>Application Crashing Events</Task><Opcode>Info</Opcode><Channel></Channel><Provider></Provider><Keywords><Keyword>Classic</Keyword></Keywords></RenderingInfo></Event></Events>
````

The exception code 0xc0000374 | 0xFFFFFFFF00000000 corresponds to the exitcode -1073740940
