### ISSUE TITLE
Runaway Process Killer Yaml: StopParentFirst uses inconsistent name

### ISSUE THREAD

**Issue by offa** [winsw/winsw#665]
The Yaml configuration of Runaway Process Killer starts with an upper case, while all other options – including the xml counterpart – start lower case.

```yml
StopParentFirst: true
```

This is really minor, but breaks consistency.

## Steps to reproduce

Create a Yaml configuration using the option ([docs](https://github.com/winsw/winsw/blob/master/doc/extensions/runawayProcessKiller.md)).

## Environment

* WinSW version: 2.10.1
* WinSW package type: all
* Windows version: all
* Wrapped executable and version: all

## Possible Solution

Change to lower case.

**Comment by NextTurn** [comment]
`stopTimeOut` in YAML is also inconsistent with `stopTimeout` in XML.

**Comment by buddhikac96** [comment]
@offa  Thank you so much for creating this.

**Comment by oleg-nenashev** [comment]
YAML support is in Preview, so we can safely fix it in the next releases. It will be a minor breaking change, though even that can be prevented if YamlDotNet supports multiple aliases
