### ISSUE TITLE
The CMD's redirected output is invalid

### ISSUE THREAD

**Issue by waltli** [winsw/winsw#679]
winsw.xml
`<configuration>`
`  <id>AccessServer</id>`
`  <name>AccessServer</name>`
`  <description>AccessServer</description>`
`  <executable>java</executable> `
`  <arguments> -Xms256m -Xmx256m  -jar access.jar > E:/start.log</arguments>`
`  <startmode>Automatic</startmode>`
`  <logpath>logs</logpath>`
`  <logmode>rotate</logmode>`
`</configuration>`

as above text "> E:/start.log", hope create a log file in E drive, but it is invalid, any way to solve it?

**Comment by NextTurn** [comment]
WinSW doesn't use a shell. You can use `logpath` and `outfilepattern`/`errfilepattern` in WinSW 2 for redirection.

**Comment by waltli** [comment]
> WinSW doesn't use a shell. You can use `logpath` and `outfilepattern`/`errfilepattern` in WinSW 2 for redirection.

thanks, 
I want to save logs that is from the standard output of **access.jar**, but the `logpath` save the winSW's log only.
example, I used `System.out.println("hello world")` in **access.jar**, and used `java -jar access.jar > E:/start.log` in CMD, then I will look this word "hello world" in E:/start.log, but in specified log file is not exist that word by `logpath`

**Comment by NextTurn** [comment]
1. `> E:/start.log` can only be handled by a shell and is therefore not supported.
1. `logpath` is a directory path.
