### ISSUE TITLE
WinSW cannot start the service for ApacheDS

### ISSUE THREAD

**Issue by jiaweizhu830** [winsw/winsw#690]
### WinSW cannot start the service when service file and winSW executable are placed in different directory

Hi!

Currently I use winSW as a service wrapper to register ApacheDS service with Windows SCM. However, I find winSW can start the ApacheDS service only when the winSW executable and configuration xml file are in the same directory with the ApacheDS files. Now I want to separate service wrapper files from the actual ApacheDS files. I wonder what causes winSW not working when I separate the files? (I points the <executable> in the xml file to the correct directory that contains ApacheDS file)

Any help is greatly appreciated!

**Comment by NextTurn** [comment]
In WinSW 3.x run `winsw <command> [<path-to-config>]`. For more information, see [CLI commands](https://github.com/winsw/winsw/blob/v3.0.0-alpha.4/docs/cli-commands.md).
