### ISSUE TITLE
Ouptut log break while stopping

### ISSUE THREAD

**Issue by sosoba** [winsw/winsw#700]
## Problem
Messages published after `CTRL+C` are truncated.

`test.yml`
```yaml
id: test
name: test
description: test
executable: node
arguments: server.js
```
`server.js`
```js
const { createServer } = require('http');

let status = 'RUN';

const httpServer = createServer((req, res) => {
  res.write(`date=${new Date().toISOString()} pid=${process.pid} status=${status}`);
  res.end();
});

httpServer.on('close', () => console.log('http.onClose', process.pid));
httpServer.listen({ port: 8080 }, () => console.log('http.onListen', process.pid));

process.on('SIGINT', () => {
  console.log('SIGINT');
  status = 'SIGINT';
  setTimeout(() => httpServer.close(), 5000); // Service exit delayed by ex. flushing resources 
});
```
`command line`
```
test.exe install
test.exe start
test.exe stop
test.exe start
test.exe stop
```
## Environment

* WinSW version: 2.10.2
* WinSW package type: .NET 4.6.1
* Windows version: 10 Pro
* Wrapped executable and version: Node 12.19.0 x64

`test.out.log`
```
http.onListen 4036
http.onListen 15180
```

expected:
```
C:>node ./server.js 
http.onListen 18572
SIGINT
http.onClose 18572
```

**Comment by NextTurn** [comment]
This looks similar to #634. I've just published v2.10.3 with the fix #680. Please let me know if the problem persists. Thanks.

**Comment by sosoba** [comment]
Dziękuję za wiadomość. W chwili obecnej przebywam na zwolnieniu lekarskim. W sprawach nie cierpiących zwłoki proszę o kontakt z Markiem Michalskim tel. 605 574 647, email: marek.michalski@coig.pl.
  
  
  
  Sławomir Osoba
Architekt Back-End

tel. (+48) 32 757 4192
tel. kom. (+48) 609 793 920
slawomir.osoba@coig.pl

 	 		 				 COIG S.A. | ul. Mikołowska 100, 40-065 Katowice | coig@coig.pl | www.coig.pl	  		 
  			Sąd Rejonowy Katowice-Wschód w Katowicach
			VIII Wydział Gospodarczy Krajowego Rejestru Sądowego KRS 0000092497,
			Kapitał zakładowy w kwocie: 5.400.000 zł, w całości wniesiony. NIP: 634-013-4205	  		

Dokument ten zawiera informacje poufne, które mogą być również objęte tajemnicą służbową. Jest on przeznaczony do wyłącznego użytku adresata.
Jeśli nie są Państwo jego adresatem, to wszelkie rozpowszechnianie, dystrybucja, reprodukcja, kopiowanie, publikacja lub wykorzystanie tego dokumentu lub informacji jest zabronione. Jeśli otrzymali Państwo tą wiadomość przez pomyłkę, prosimy o bezzwłoczne skontaktowanie się z nami oraz usunięcie wiadomości z Państwa komputera.  

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail by mistake) please notify the sender immediately and destroy this email. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
