### ISSUE TITLE
looks like <serviceaccount> tag doesnt work

### ISSUE THREAD

**Issue by akurets** [winsw/winsw#703]
**Need to install service as user, add appropriate tag in xml config, but nothing happen**

## Steps to reproduce

1) build spring boot executable jar
2) follow winsw documentation
3) add <serviceaccount> tag, trying different approaches with prompt and username
4) install service

bellow my last config

```xml
<service>
    <id>omni-service</id>
    <name>omni-service</name>
    <description>omni-sign service as windows service example</description>
    <executable>%BASE%\jre8u272\bin\java</executable>
    <arguments>-jar "%BASE%\omniSign.jar"</arguments>
    <logmode>rotate</logmode>
    <serviceaccount>
        <username>.\UserName</username>
        <password>Pa55w0rd</password>
        <allowservicelogon>true</allowservicelogon>
    </serviceaccount>
</service>
```

## Environment

* WinSW version: v3.0.0-alpha.5
* WinSW package type: NETCore.x64
* Windows version: win10
* Wrapped executable and version: "internal project"

## Possible Solution

have no idea(

**Comment by NextTurn** [comment]
I can't reproduce it. Was the service installed? What's the console output? Can you provide a screenshot of the service please?

![image](https://user-images.githubusercontent.com/45985406/97516977-47e44900-19cf-11eb-9966-76ad3dc63d3f.png)

**Comment by akurets** [comment]
hey, thanx for speedy feedback.

below console output with above config, when install and start service.
and properties screenshot.

![photo_2020-10-29_10-50-37](https://user-images.githubusercontent.com/56323786/97540879-2a59b400-19bc-11eb-9097-aa3361475608.jpg)
![photo_2020-10-29_10-52-07](https://user-images.githubusercontent.com/56323786/97540881-2af24a80-19bc-11eb-8483-c51147b4d7ff.jpg)

maybe you need smth else for clarifying?
any way, i am sorry i am not familiar with windows)

**Comment by azryelryvel** [comment]
I had the same problem.
The documentation is up-to-date with 3.0 whereas i downloaded the last stable version which is still 2.x
If that was your case, you need to user the <user> and <domain> tags separately instead of <username>

see number 7 in this document
https://github.com/winsw/winsw/blob/v3/docs/migrate-to-3-x.md

**Comment by NextTurn** [comment]
Like @azryelryvel said you must have downloaded the wrong version. The expected output looks like:

```
>WinSW.exe install
00:00:00,000 - Installing service 'omni-service (omni-service)'...
00:00:00,000 - Service 'omni-service (omni-service)' was installed successfully.
```
