### ISSUE TITLE
blue screen after killing service when reboot action is configured

### ISSUE THREAD

**Issue by zhang98722** [winsw/winsw#705]
when i do the SLA test meet this issue
its a simple java springboot+springmvc project
install and start gone well
then i just killed the java.exe to tell if winsw would restart it as normal watch dog always do
first kill, work well
second kill, work well too
third kill, boom, blue screen show up and told me
CRITICAL_PROCESS_DIED

```xml
<service>
    <id>demo_service</id>
    <name>demo_service</name>
    <description>This service is a service created from a sample configuration</description>
    <executable>java</executable>
    <onfailure action="restart" delay="10 sec"/>
    <onfailure action="restart" delay="20 sec"/>
    <onfailure action="reboot" />
    <arguments> -jar D:\demo-a-0.0.1-SNAPSHOT.jar</arguments>
    <priority>Normal</priority>
    <stoptimeout>15 sec</stoptimeout>
    <stopparentprocessfirst>true</stopparentprocessfirst>
    <startmode>Automatic</startmode>
    <waithint>15 sec</waithint>
    <sleeptime>1 sec</sleeptime>
    <logpath>%BASE%\logs</logpath>
    <log mode="append"></log>
</service>
```

## Environment

* WinSW version: 2.10.3
* WinSW package type: NET4.exe
* Windows version: WIN10 LTSC
* Wrapped executable and version: simple java springboot+spring mvc

## Possible Solution

not sure what happened, checked system log ,but nothing found

**Comment by zhang98722** [comment]
seems its about the onfailure config
if only configed as:
  <onfailure action="restart" delay="10 sec"/>
then it could work fine

**Comment by NextTurn** [comment]
Though it looks terrifying this is the expected behavior.
