### ISSUE TITLE
Application doesn't seem to work as expected or described in the documentation

### ISSUE THREAD

**Issue by AzureusPT** [winsw/winsw#720]
**Summary**. The application should install the service, but instead it just crashes requesting a missing XML/YML file.

## Steps to reproduce

1. Download WinSW v2.10.3, in my case I've tried both `WinSW.NET4.exe` and `WinSW.NET461.exe`
2. Generate your XML according to the documentation.
3. Run the command to install it: `WinSW.NET4.exe install <filename.xml>`
4. The program seems to crash asking for another XML/YML file instead of installing the service.
```
PS > .\WinSW.NET461.exe install .\app.xml
System.IO.FileNotFoundException: Unable to locate WinSW.NET461.[xml|yml] file within executable directory
   at WinSW.Program.GetServiceDescriptor()
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
```

## XML file used

Not sure if this is important, since it seems its not even trying to read it, but this is the content of the XML file I'm using:
```
<service>
  <id>someid</id>
  <name>Some Name</name>
  <description>Blah blah</description>
  <executable>powershell</executable>
  <arguments>"%BASE%\script.ps1"</arguments>
  <log mode="roll"></log>
</service>
```

## Environment

* WinSW version: 2.10.3
* WinSW package type: .NET 4.6.1, .NET 4
* Windows version: Windows 10, Windows Server 2019
* Wrapped executable and version: I'm calling a PowerShell script

**Comment by NextTurn** [comment]
Sorry for the inconvenience but the command-line syntax in 2.x is `winsw install` (without the path) at the moment.

**Comment by AzureusPT** [comment]
Maybe I'm missunderstanding something, but `winsw` won't work by itself if the executable is named `WinSW.NET461.exe`. Also renaming `WinSW.NET461.exe` to `winsw.exe` results in the same issue. Do I have to install this exe or do something else?

**Comment by NextTurn** [comment]
Well, I was just referring to `whatever.exe install` with *whatever.xml* next to it.

**Comment by AzureusPT** [comment]
Ok, now I get it, so `<filename.xml>` has to be renamed as the same name as the executable we download (but `.xml` instead of `.exe`).

Thanks for the clarification.

**Comment by NextTurn** [comment]
You may have missed the [installation guide](https://www.github.com/winsw/winsw/tree/master/doc/installation.md) 2.x.
