### ISSUE TITLE
[Help Wanted] Starting WinSW in CLI mode

### ISSUE THREAD

**Issue by koraniar** [winsw/winsw#723]
### Problem statement
I have renamed `WinSW.exe` to `vtulservice.exe`

The process to register the .exe as service was:
1. Run `vtulservice.exe install`.
2. Run `vtulservice.exe start`.

I made the same process in 5 devices, and everything works in four of them, but in the other one the service does not start and it creates this log:
<img width="815" alt="Screen Shot 2020-11-20 at 13 05 38" src="https://user-images.githubusercontent.com/17574419/99970807-5cb3c280-2d6a-11eb-9052-f98e5906758e.png">

I have limited access to this device so I cannot make a lot of tests, currently, I am using WinSW 2.9.0.

Do you know why it could have this behavior in only one device?

**Comment by NextTurn** [comment]
Not pretty sure what was wrong there... Maybe you could try 2.10.3?

**Comment by NextTurn** [comment]
This may have been fixed in 2.10.1 by #660 if you set `allowservicelogon` to `true`.

**Comment by koraniar** [comment]
@NextTurn thanks for your fast response!

I do not use this tag, is this tag by default true?
Do you know what other things could make this problem happen?

I will test with version 2.10.3 as soon I get access to the device.

**Comment by koraniar** [comment]
I forgot one step in the process, the process is:
1. Run `vtulservice.exe uninstall`.
2. Run `vtulservice.exe install`.
3. Run `vtulservice.exe start`.

We first try to uninstall a previous version of the service before trying to install the latest version

**Comment by NextTurn** [comment]
It was false by default. Hmm, I can't think of another known bug that can crash the console process.

Could you please check the exit codes (`%ERRORLEVEL% in Command Prompt or `$?` in PowerShell) of the failed commands?

**Comment by koraniar** [comment]
I could not replicate the error, in my last test on this computer everything works well with the same version 2.9.0.

So I will close the issue until I see it again.
Thank you for your help @NextTurn
