### ISSUE TITLE
Configuration Error?

### ISSUE THREAD

**Issue by arodriguezbg** [winsw/winsw#734]
**Current configuration:**

```xml
<service>
<id>JenkinsSlave_W</id>
  <name>JenkinsSlave_W</name>
  <description>This service runs an agent for Jenkins automation server.</description>
  <executable>"C:\Program Files\Java\jre1.8.0_201\bin\java.exe"</executable>
  <arguments>-Xrs -jar "%BASE%\agent.jar" -jnlpUrl http://x.x.x.x:8080/computer/Agent_nmknte805/slave-agent.jnlp -secret xyz -workDir E:\JenkinsAgentWrapper</arguments>
  <logmode>rotate</logmode>
  <onfailure action="restart">
    <download from="http://x.x.x.x:8080/jnlpJars/agent.jar" to="%BASE%\agent.jar">
      <extensions>
        <extension classname="winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension" enabled="true" id="killOnStartup">
          <pidfile>%BASE%\jenkins_agent.pid</pidfile>
          <stoptimeout>5000</stoptimeout>
          <stopparentfirst>false</stopparentfirst>
        </extension>
      </extensions>
    </download>
  </onfailure>
</service>
```

**Get the following output from Event Viewer when I try to run the service**

Service cannot be started. System.IO.InvalidDataException: Attribute <className> is missing in configuration XML
   at winsw.Util.XmlHelper.SingleAttribute[TAttributeType](XmlElement node, String attributeName)
   at winsw.Extensions.WinSWExtensionDescriptor.FromXml(XmlElement node)
   at winsw.Extensions.WinSWExtensionManager.LoadExtension(String id)
   at winsw.Extensions.WinSWExtensionManager.LoadExtensions()
   at winsw.WrapperService.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

**If I execute what the service is trying to execute manually; it works alright, any idea what might be wrong in my xml?**

**Comment by NextTurn** [comment]
> `Service cannot be started. System.IO.InvalidDataException: Attribute <className> is missing in configuration XML`

As the error message indicated `classname` should be renamed to `className`.

**Comment by arodriguezbg** [comment]
Fantastic! Thanks for the quick reply... Everything is working now! 👍

**Comment by NextTurn** [comment]
In addition, I suggest not writing nested XML elements like this.. Such syntax is not guaranteed to work in the future.
