### ISSUE TITLE
java as service - error 1067 when starting

### ISSUE THREAD

**Issue by FGautard** [winsw/winsw#739]
I am trying to use winsw to start a jar as a Windows Service. For now, I'm trying on a simple Hello World Spring Boot Application. 
I manage to install the service but when I try to start the service I got an error 1067

![image](https://user-images.githubusercontent.com/27813973/101534774-aa811b00-3965-11eb-9294-c4160dbdf13c.png)

My log file is not really usefull :
2020-12-08 14:51:08,235 INFO  - Installing service 'MyApp (MyApp)'...
2020-12-08 14:51:08,256 INFO  - Service 'MyApp (MyApp)' was installed successfully.
2020-12-08 14:51:18,283 DEBUG - Starting WinSW in service mode.
2020-12-08 14:51:18,303 INFO  - Starting java
2020-12-08 14:51:18,359 INFO  - Started process java (22364).
2020-12-08 14:51:18,378 INFO  - Service started successfully.
2020-12-08 14:51:18,381 WARN  - Child process 'java (22364)' finished with code -1073741502.

All my files are on the same folder as follow :
![image](https://user-images.githubusercontent.com/27813973/101535565-d8b32a80-3966-11eb-8e61-777135873b4a.png)

And my xml configuration is the following :

`<service>`
`    <id>MyApp</id>`
`    <name>MyApp</name>`
`    <description>This runs Spring Boot as a Service.</description>`
`    <executable>java</executable>`
`    <arguments>-jar "%BASE%\MyApp.jar"</arguments>`
`    <logmode>rotate</logmode>`
`    <logpath>%BASE%\logs\</logpath>`
`</service>`

I try with the full path to the java.exe also but I have the same issue.
Any idea what my be wrong in my configuration ?

**Comment by NextTurn** [comment]
STATUS_DLL_INIT_FAILED... What's your OS version and Java bitness (64-/32-bit) please?

**Comment by FGautard** [comment]
I'm on Windows 10 with a java 1.8 32 bits

**Comment by NextTurn** [comment]
Thanks. Which version of Windows 10 please?

**Comment by FGautard** [comment]
Windows 10 Professional (version 1909)

**Comment by NextTurn** [comment]
Could you try [this patch](https://dev.azure.com/winsw/winsw/_build/results?buildId=732&view=artifacts&pathAsName=false&type=publishedArtifacts) with the same config and see if it fixes the issue?

**Comment by FGautard** [comment]
Thank you for your quick response.
But unfortunately I still have the same error.
The only difference is that the `MyApp_service.exe start` command is now returning a `Failed to start the service.` message

**Comment by FGautard** [comment]
Well I hava a good news, I install some Windows update that were available and it's working !

Thank you for your time and your quick support !

**Comment by NextTurn** [comment]
I'm happy to hear that, but what updates did you install? This information may be helpful to similar issues in the future, thanks!

**Comment by FGautard** [comment]
Yes indeed, apparently that was the update KB4592449 for Windows 10.

**Comment by NextTurn** [comment]
> Addresses a security vulnerability by preventing applications that run as a SYSTEM account from printing to “FILE:” ports. To address this issue in the future, make sure your applications or services run as a specific user or service account.

Who knows what the update has to do with this? Anyway thanks for following up on the issue!

**Comment by dyorgio** [comment]
> > Addresses a security vulnerability by preventing applications that run as a SYSTEM account from printing to “FILE:” ports. To address this issue in the future, make sure your applications or services run as a specific user or service account.
> 
> Who knows what the update has to do with this? Anyway thanks for following up on the issue!

I'm having the same issue with machines after this update, but only when I call myService.exe install from a msi installer.
In this cenario I received "Cannot connect in process console output".

I tried to change user to LocalService, but no luck.
