### ISSUE TITLE
RunawayProcessKiller

### ISSUE THREAD

**Issue by CampeloMarcos** [winsw/winsw#741]
Hi,

I'm getting this error when installing the service.

```
An assembly specified in the application dependencies manifest (WindowsService.deps.json) was not found:
    package: 'RunawayProcessKiller', version: '2.8.0'
    path: 'RunawayProcessKiller.dll'

```
Windows 10 pro 32bits

**Comment by oleg-nenashev** [comment]
Strange. There should be no special binary for that, this DLL is merged into the main executable using IlMerge. Which .NET version and which executable are you running?

**Comment by CampeloMarcos** [comment]
I have a setup that installs the service, with that all the popup are hidden and due to UAC being configured to ask about any changes, the dll was not copied.

Issue resolved by disabling UAC
