### ISSUE TITLE
Service XML file *always* has to be provided and have same name as WinSW executable

### ISSUE THREAD

**Issue by richmilne** [winsw/winsw#805]
# Summary
The main README, under the section "Use WinSW as a global tool" implies the executable and service file can have different names. To quote, "3. Run `winsw install myapp.xml [options]` to install the service."

This doesn't work in practice - the executable throws an exception saying it can't find the service file with the same name as itself.

Similarly, even when you try and call commands that shouldn't require a service file (like `help` or `version`), they won't work unless there is an XML file present with the same name as the executable.

## Steps to reproduce
The `C:\bin` dir contains the service wrapper executable, `WinSW.exe`, and the config file, `myapp.xml`.

```
C:\bin>WinSW.exe status myapp.xml
System.IO.FileNotFoundException: Unable to locate WinSW.[xml|yml] file within executable directory or any parents
   at WinSW.Program.GetServiceDescriptor()
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
```
```
C:\bin>WinSW.exe version
System.IO.FileNotFoundException: Unable to locate WinSW.[xml|yml] file within executable directory or any parents
   at WinSW.Program.GetServiceDescriptor()
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
```
```
C:\bin>ren myapp.xml WinSW.xml
```
```
C:\bin>WinSW version
WinSW 2.10.3.0
```

I also tried the very first version for which I could find a downloadable executable - v2.0.0 - and it had the same error. Maybe separate exe/xml names was a v1.x feature only?

## Environment

* WinSW version: WinSW v2.10.3
* WinSW package type: all of them
* Windows version: Windows Server 2012 R2 Standard
* Wrapped executable and version: internal project

**Comment by nxtn** [comment]
> **Please refer to the [v2](https://github.com/winsw/winsw/tree/master) branch for previous version documentation.**
