### ISSUE TITLE
.NET6 runtime not found

### ISSUE THREAD

**Issue by SekiBetu** [winsw/winsw#810]
already installed the .NET6 SDK(include runtime), but still shows not installed
![image](https://user-images.githubusercontent.com/38283893/111479173-b140da80-876b-11eb-8207-47cdc7acd9b9.png)

```
Error:
  An assembly specified in the application dependencies manifest (WinSW.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '6.0.0-preview.2.21154.6'
    path: 'mscordaccore.dll'
```

## Steps to reproduce

1、the .exe file and xml file in the same dir with WinSW.exe
2、use poweshell 7.1.3 and use command ".\WinSW.exe install", then the Error happens

```xml
<service>
  <id>XXXXX</id>
  <name>XXXXX</name>
  <description>XXXXX</description>
  <executable>XXXXX.exe</executable>
  <arguments>-p 11111</arguments>
</service>
```

## Environment

* WinSW version: WinSW v3.0.0-alpha.8
* WinSW package type: SDK 6.0.100-preview.2
* Windows version: WIN10 19043.867
* Wrapped executable and version: a nodejs executable file which packed by pkg

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/111480642-2b259380-876d-11eb-9521-9b93678b3c6c.png)
by the way, i installed the 2 different version of .NET runtime, maybe winsw found the wrong one?

**Comment by SekiBetu** [comment]
.NET 6 Preview 3 is out，should we update the dependencies？ it seems the WinSW v3.0.0-alpha.8 can only running under .NET 6 Preview 2

```
Error:
  An assembly specified in the application dependencies manifest (WinSW.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '6.0.0-preview.2.21154.6'
    path: 'mscordaccore.dll'
```

**Comment by nxtn** [comment]
.NET 6 Preview 3 just seems worse. I'll revert #806 in #817.
