### ISSUE TITLE
Move CLI parsing and Service host code to different classes

### ISSUE THREAD

**Issue by carpnick** [winsw/winsw#83]
Hard to tell what is going on in Main.cs since it both does service hosting and CLI parsing.

Also remove as much functionality as possible from Run() to make it easier to test from UnitTests.
This should be in scope for 2.0

**Comment by oleg-nenashev** [comment]
I would also vote to have a standard CLI parser if there is a need to get much more options and commands in CLI.

**Comment by oleg-nenashev** [comment]
will do it after the initial release of WinSW 2.0
