### ISSUE TITLE
Cannot provision services using virtual service accounts (NT Service)

### ISSUE THREAD

**Issue by prenetic** [winsw/winsw#835]
When installing a service using the domain "NT SERVICE" and a username which matches the ID of the service itself and no password (the username must match the service ID, and the password must be blank), the expectation is that the "Log On As" username should reflect a virtual account. What is happening instead is the service gets created with "Local System" for the "Log On As" user, requiring manual configuration to correct this following service installation. Virtual accounts are convenient and supported in other service wrappers, namely "nssm".

https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/service-accounts#virtual-accounts

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd548356(v=ws.10)#using-virtual-accounts

## Steps to reproduce

Install the sample service as outlined below and observe the "Log On As" account details.

```xml
<service>
  <id>MyExampleService</id>
  <executable>powershell.exe</executable>
  <name>My Example Service</name>
  <serviceaccount>
    <domain>NT Service</domain>
    <user>MyExampleService</user>
    <password></password>
    <allowservicelogon>true</allowservicelogon>
  </serviceaccount>
  <arguments>-file .\start.ps1</arguments>
  <workingdirectory>C:\Program Files\MyExampleService</workingdirectory>
  <interactive>false</interactive>
</service>
```

As-is upon service installation (without intervention):
![image](https://user-images.githubusercontent.com/11982895/120880751-062d0980-c581-11eb-9aeb-06596957a553.png)
![image](https://user-images.githubusercontent.com/11982895/120880757-0d541780-c581-11eb-8655-a8f48e8f4926.png)
![image](https://user-images.githubusercontent.com/11982895/120880762-1218cb80-c581-11eb-9a57-22512dfc11df.png)

After correcting this manually (what should be automatically provisioned):
![image](https://user-images.githubusercontent.com/11982895/120880820-6fad1800-c581-11eb-98c7-af81de00d790.png)
![image](https://user-images.githubusercontent.com/11982895/120880823-763b8f80-c581-11eb-8cb4-bf2032ee4f23.png)
(shows obscured password even though in actuality it is blank)

## Environment

* WinSW version: 3.0.0+25b5d7a741ed3eeb5502afc6b039bca4e41dec7f
* WinSW package type: Standalone binary (WinSW-x64.exe)
* Windows version: Windows Server 2019 (Version 1809)
* Wrapped executable and version: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

## Possible Solution

Enable users to specify "NT Service" as the domain with a username matching the ID of the service, and/or include an option to use a virtual account instead of a typical service account where WinSW automatically takes care of the account details.

**Comment by nxtn** [comment]
See #703

**Comment by prenetic** [comment]
Thanks, I must have somehow wound up looking at documentation for 2.0. Changing `<user>` to `<username>` and removing `<password>` resolved my issue.

**Comment by prenetic** [comment]
Just wanted to follow-up on this one. I looked back and found I was referring to [this sample config](https://github.com/winsw/winsw/blob/v3/samples/complete.xml) when installing my services. The latest commit appears to be part of a pull request to [update documentation for 3.0.0-alpha.7](https://github.com/winsw/winsw/pull/731) which led to my confusion, as this sample config still contains the old `<domain>` and `<user>` tags.
