### ISSUE TITLE
Please do not add quotes automatically <argument> parameter

### ISSUE THREAD

**Issue by wangdakanga** [winsw/winsw#89]
Please do not add quotes automatically <argument> parameter
Sorry, I do not speak English. This is my first time to ask questions on github.
This is a Google translation of content
When I try to use your program will nginx configuration for service
Configured as follows:
<code>
  &lt;Id&gt; nginx &lt;/ id&gt;<br/>
  &lt;Name&gt; nginx &lt;/ name&gt;<br/>
  &lt;Description&gt; nginx &lt;/ description&gt;<br/>
  &lt;Executable&gt; E: \ App \ nginx-1.7.10 \ nginx.exe &lt;/ executable&gt;<br/>
  &lt;Workingdirectory&gt; E: \ App \ nginx-1.7.10 \ &lt;/ workingdirectory&gt;<br/>
  &lt;Logpath&gt; E: \ App \ Service \ log &lt;/ logpath&gt;<br/>
  &lt;Logmode&gt; append &lt;/ logmode&gt;<br/>
  &lt;Depend&gt; &lt;/ depend&gt;<br/>
  &lt;Startargument&gt; &lt;/ startargument&gt;<br/>
  &lt;Stopexecutable&gt; E: \ App \ nginx-1.7.10 \ nginx.exe &lt;/ stopexecutable&gt;<br/>
  &lt;Stopargument&gt; -s stop &lt;/ stopargument&gt;<br/>
</code>
(Sorry, I do not know how to display the contents)

Nignx always found can not stop
Log contents "nginx: invalid option:" -s stop ""
It will merge -s stop for a parameter
I think that this will reduce the flexibility of the design 

The following is the Chinese text:
请不要在<argument>参数中自动添加引号
很抱歉,我不会英语。这是我第一次在github上提问题。
这是谷歌翻译的内容
当我在尝试使用您的程序将nginx配置为服务时
配置如下：
  <code>
  &lt;Id&gt; nginx &lt;/ id&gt;<br/>
  &lt;Name&gt; nginx &lt;/ name&gt;<br/>
  &lt;Description&gt; nginx &lt;/ description&gt;<br/>
  &lt;Executable&gt; E: \ App \ nginx-1.7.10 \ nginx.exe &lt;/ executable&gt;<br/>
  &lt;Workingdirectory&gt; E: \ App \ nginx-1.7.10 \ &lt;/ workingdirectory&gt;<br/>
  &lt;Logpath&gt; E: \ App \ Service \ log &lt;/ logpath&gt;<br/>
  &lt;Logmode&gt; append &lt;/ logmode&gt;<br/>
  &lt;Depend&gt; &lt;/ depend&gt;<br/>
  &lt;Startargument&gt; &lt;/ startargument&gt;<br/>
  &lt;Stopexecutable&gt; E: \ App \ nginx-1.7.10 \ nginx.exe &lt;/ stopexecutable&gt;<br/>
  &lt;Stopargument&gt; -s stop &lt;/ stopargument&gt;<br/>
</code>
(对不起，我不知道如何展示该内容)
发现nignx始终都无法停止
日志内容 “nginx: invalid option: "-s stop" “
它将 -s stop合并为了一个参数
我认为这样设计会降低程序的灵活度

**Comment by oleg-nenashev** [comment]
I suppose the behavior is valid. WinSW triggers a system call by 
BTW, it makes sense to have "startargunent_params/stopargument_params" options or to somehow modify the behavior.

**Comment by 2933280** [comment]
i have a similar problem

\<argument\>-jar %BASE%\bin\myjar-with-dependencies.jar\</argument\> didn't work

my workaround: split into 2 lines
\<argument\>-jar\</argument\>
\<argument\>%BASE%\bin\myjar-with-dependencies.jar\</argument\>

**Comment by rui-paz** [comment]
Hi,

It would be nice if this issue got fixed! It doesn't make any sense to quotes around arguments because it becomes only one argument to the exe instead of several!

@2933280: Thanks for your suggestion but <stoparguments> doesn't seems to exist and also several <stopargument> lines are ignored according to my testing!

**Comment by manfrede** [comment]
I made this little change to winsw.ServiceDescriptor.cs to have stoparguments/startarguments as described in sample-allOptions.xml for one line arguments. If those are not set it will fallback to stopargument/startargument.

```
        public string Startargument
        {
            get
            {
                return AppendTags("startargument", Defaults.Startarguments);
            }
        }

        public string Startarguments
        {
            get
            {
                var args = SingleElement("startarguments", true);
                return String.IsNullOrEmpty(args) ? Startargument : args;
            }
        }

        public string Stopargument
        {
            get
            {
                return AppendTags("stopargument", Startarguments);
            }
        }

        public string Stoparguments
        {
            get
            {
                var args = SingleElement("stoparguments", true);
                return String.IsNullOrEmpty(args) ? Stopargument : args;
            }
        }
```

**Comment by oleg-nenashev** [comment]
@manfrede please create a pull request

**Comment by NextTurn** [comment]
Please use \<argument**s**\>/\<startargument**s**\>/\<stopargument**s**\> (with an additional **s**).

**Comment by NextTurn** [comment]
\<argument\>/\<startargument\>/\<stopargument\> is designed for individual arguments.

\<argument**s**\>/\<startargument**s**\>/\<stopargument**s**\> is for multiple arguments. \<argument**s**\> is supported in all versions of WinSW. \<startargument**s**\>/\<stopargument**s**\> is supported since 2.9.0.

(I hope you can see this.)
