### ISSUE TITLE
Enable ReadyToRun for better startup time

### ISSUE THREAD

**Issue by zhzy0077** [winsw/winsw#941]
### Feature Request

**Problem statement.**
I'm not sure if it aligns with the direction of winsw so open this issue rather than a PR.
As a console app, ReadyToRun really helps it's startup time as no JIT is required.
In my middle-end device, including `-p:PublishReadyToRun=true` in `publish` give below perf diff:
```
Measure-Command { .\WinSW-ReadyToRun.exe --help} 
453 milliseconds.

Measure-Command { .\WinSW.exe --help} 
3 seconds 442 milliseconds.
```

**Describe the solution you'd like.**
[ReadyToRun Docs](https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run)

**Comment by nxtn** [comment]
Thanks for the advice. This is mainly due to self-extracting on .NET 5. It is much faster now on .NET 6/7.

```
> Measure-Command { .\WinSW-x64.exe --help }
TotalMilliseconds : 284.0221
```

R2R dramatically increases the binary size (from 17.4 MB to 36.7 MB), so I do not favor it in this project.
