### ISSUE TITLE
Could not start service; No such file or directory

### ISSUE THREAD

**Issue by Phrogz** [winsw/winsw#96]
Here's my config XML file:

``` xml
<service>
  <id>cxintents</id>
  <name>cxintents</name>
  <description>cxintents web service</description>
  <executable>c:\Ruby\bin\ruby.exe</executable>
  <workingdirectory>c:\www\cxintents</workingdirectory>
  <logpath>c:\www\cxintents\logs</logpath>
  <logmode>roll</logmode>
  <depend></depend>
  <startargument>c:\Ruby\bin\thin start -p 3101 -e production</startargument>
  <stopargument>c:\Ruby\bin\thin stop</stopargument>
</service>
```

The service installed OK. When I tried to start the service, it generated this error log entry:

```
c:\Ruby\bin\ruby.exe: No such file or directory -- c:/Ruby/bin/thin start -p 3101 -e production (LoadError)
```

However, if I run the same executable/argument combination from that working directory it works fine:

```
C:\www\cxintents>c:\Ruby\bin\ruby.exe c:/Ruby/bin/thin start -p 3101 -e production
Using rack adapter
No change to public/blob.js
No change to public/blob.css
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3101, CTRL+C to stop
Stopping ...
```

**Comment by Phrogz** [comment]
As a **workaround**, instead of `<startargument>` I was able to use these `<argument>` lines:

~~~xml
  <argument>c:\Ruby\bin\thin</argument>
  <argument>-p 3101</argument>
  <argument>-e production</argument>
  <argument>start</argument>
~~~

**Comment by pnikonowicz** [comment]
I suggest the following behavior is implemented:
1) WHEN the `<argument>` section is missing 
AND there are spaces in the `<startargument>`
THEN parse the options and treat them as additional arguments
2) WHEN the `<argument>` section is NOT missing 
AND there are spaces in the `<startargument>`
THEN error with the message "You can not have both additional arguments in the `<startargument>` and the `<argument>` section.

**Comment by NextTurn** [comment]
Please place only one argument per \<argument\>/\<startargument\>.

\<startarguments\> is supported since 2.9.0.
