### ISSUE TITLE
winsw.exe install myapp.xml is not working

### ISSUE THREAD

**Issue by garunc** [winsw/winsw#970]
version :winsw.exe 2.11

command line : when i run winsw.exe install myapp.xml 

Exception: Unable to locate winsw.xml|yml file with executable directory

Please can some one help me.

When i tried to winsw.exe install it works ,provide xml name is winsw.xml .

As i need to install multiple services when i tried like mentioned in documentation it does not work.

Example : app.exe install app.xml ->works
app.exe is rename of winsw.exe then it works

Example 2:winsw.exe install myapp.xml -> doesnot work

Xml file Example
```
<service>
   <id>appname</id>
    <name>appname is</name>
    <description>connectivity</description>
<executable>%BASE\my.exe</executable>
<log mode="roll"></log>
</service>```

**Comment by Vzz1c** [comment]
Same problem Global tools not working,I don't understand what the problem is with this, why do I need a separate xml configuration file for each application? Can a configuration like the one below be implemented?



<services>
 <service>
...
</service>
</services>

**Comment by Vzz1c** [comment]
services
 service
...
/service
/services

**Comment by alfabravoteam** [comment]
According to the official documentation https://github.com/winsw/winsw/blob/master/doc/installation.md 

The first step is to rename the exe to whatever you find suitable and THEN, set an xml with the same name as the exe, in the same folder. So yes, that is the expected behavior.
